export const PASSWORD_HASHER = 'PASSWORD_HASHER';
export const TOKEN_SERVICE = 'TOKEN_SERVICE';
export const REFRESH_TOKEN_REPOSITORY = 'REFRESH_TOKEN_REPOSITORY';
export const EMAIL_VERIFICATION_TOKEN_REPOSITORY = 'EMAIL_VERIFICATION_TOKEN_REPOSITORY';
export const EMAIL_SENDER = 'EMAIL_SENDER';
