// Les sorts de niveau 0 et 1 de D&D 2024 — le seul périmètre qu'une fiche de
// niveau 1 peut consommer.
// Source : docs/characteres/spells.seed.json et spells.effects.json (extraction AideDD),
// filtrés et normalisés. Les niveaux 2 à 9 attendront le niveau 3 des personnages.
//
// Fichier volumineux et mécanique : il se relit par diff, pas à l'œil.

import type { Ability } from './abilities';
import type { ClassKey, SpellKey } from './keys';
import type { DamageType } from './proficiencies';

export const SPELL_SCHOOLS = [
  'abjuration',
  'conjuration',
  'divination',
  'enchantment',
  'evocation',
  'illusion',
  'necromancy',
  'transmutation',
] as const;

export type SpellSchool = (typeof SPELL_SCHOOLS)[number];

export interface SpellComponents {
  verbal: boolean;
  somatic: boolean;
  material: string | null;
}

export interface SpellSave {
  ability: Ability;
  onSuccess: string;
}

export interface SpellDamage {
  dice: string;
  type: DamageType;
  attackRoll: boolean;
  save: SpellSave | null;
}

export interface Spell {
  key: SpellKey;
  name: string;
  level: 0 | 1;
  school: SpellSchool;
  castingTime: string;
  range: string;
  components: SpellComponents;
  duration: string;
  concentration: boolean;
  ritual: boolean;
  classLists: readonly ClassKey[];
  damage: SpellDamage | null;
  description: string;
}

const SPELL_LIST: readonly Spell[] = [
  {
    key: "acid-splash",
    name: "Aspersion d'acide",
    level: 0,
    school: "evocation",
    castingTime: "Action",
    range: "18 m",
    components: { verbal: true, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["sorcerer", "wizard"],
    damage: { dice: "1d6", type: "acid", attackRoll: false, save: { ability: "dexterity", onSuccess: "none" } },
    description: "Vous créez une bulle acide en un point à portée, où elle explose dans une Sphère de 1,50 mètre de rayon. Toute créature dans cette Sphère doit réussir un jet de sauvegarde de Dextérité ou subir 1d6 dégâts d'acide. Amélioration de sort mineur. Les dégâts augmentent de 1d6 lorsque vous atteignez les niveaux 5 (2d6), 11 (3d6) et 17 (4d6).",
  },
  {
    key: "alarm",
    name: "Alarme",
    level: 1,
    school: "abjuration",
    castingTime: "1 minute ou Rituel",
    range: "9 m",
    components: { verbal: true, somatic: true, material: "une coche et du fil d'argent" },
    duration: "8 heures",
    concentration: false,
    ritual: true,
    classLists: ["ranger", "wizard"],
    damage: null,
    description: "Vous mettez en place une alarme contre les intrusions. Choisissez une porte, une fenêtre ou une zone à portée ne dépassant pas un Cube de 6 mètres de côté. Jusqu'à la fin du sort, une alarme vous alerte dès qu'une créature touche ou pénètre dans la zone protégée. Lorsque vous lancez le sort, vous pouvez désigner des créatures qui ne déclencheront pas l'alarme. Vous pouvez également choisir si l'alarme est sonore ou mentale : Alarme sonore. L'alarme produit le son d'une clochette qui s'entend dans un rayon de 18 mètres autour de la zone protégée pendant 10 secondes. Alarme mentale. Vous êtes alerté par un signal mental si vous vous trouvez à moins de 1,5 km de la zone protégée. Ce signal vous réveille si vous dormez.",
  },
  {
    key: "animal-friendship",
    name: "Amitié avec les animaux",
    level: 1,
    school: "enchantment",
    castingTime: "Action",
    range: "9 m",
    components: { verbal: true, somatic: true, material: "un peu de nourriture" },
    duration: "24 heures",
    concentration: false,
    ritual: false,
    classLists: ["bard", "druid", "ranger"],
    damage: null,
    description: "Ciblez une bête que vous pouvez voir à portée. La cible doit réussir un jet de sauvegarde de Sagesse ou subir l'état Charmé pendant toute la durée du sort. Si vous ou l'un de vos alliés infligez des dégâts à la cible, le sort prend fin.",
  },
  {
    key: "armor-of-agathys",
    name: "Armure d'Agathys",
    level: 1,
    school: "abjuration",
    castingTime: "Action bonus",
    range: "Perso",
    components: { verbal: true, somatic: true, material: "un éclat de verre bleu" },
    duration: "1 heure",
    concentration: false,
    ritual: false,
    classLists: ["warlock"],
    damage: { dice: "5", type: "cold", attackRoll: false, save: null },
    description: "Un givre magique protecteur vous enveloppe. Vous gagnez 5 points de vie temporaires. Si une créature vous touche avec un jet d'attaque au corps à corps avant la fin du sort, elle subit 5 dégâts de froid. Le sort prend fin prématurément si vous n'avez plus de points de vie temporaires.",
  },
  {
    key: "arms-of-hadar",
    name: "Tentacules de Hadar",
    level: 1,
    school: "conjuration",
    castingTime: "Action",
    range: "Perso",
    components: { verbal: true, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["warlock"],
    damage: { dice: "2d6", type: "necrotic", attackRoll: false, save: { ability: "strength", onSuccess: "half" } },
    description: "En invoquant Hadar, vous faites jaillir des vrilles de votre corps. Chaque créature dans une Émanation de 3 mètres provenant de vous effectue un jet de sauvegarde de Force. En cas d'échec, la cible subit 2d6 dégâts nécrotiques et ne peut plus prendre de Réactions avant le début de son prochain tour. En cas de réussite, la cible subit seulement la moitié des dégâts.",
  },
  {
    key: "bane",
    name: "Imprécation",
    level: 1,
    school: "enchantment",
    castingTime: "Action",
    range: "9 m",
    components: { verbal: true, somatic: true, material: "une goutte de sang" },
    duration: "Concentration, jusqu'à 1 minute",
    concentration: true,
    ritual: false,
    classLists: ["bard", "cleric", "warlock"],
    damage: null,
    description: "Jusqu'à trois créatures de votre choix que vous pouvez voir à portée doivent chacune effectuer un jet de sauvegarde de Charisme. Lorsqu'une cible qui rate ce jet de sauvegarde effectue un jet d'attaque ou de sauvegarde avant la fin du sort, elle doit soustraire 1d4 à son jet d'attaque ou de sauvegarde.",
  },
  {
    key: "blade-ward",
    name: "Voile défensif",
    level: 0,
    school: "abjuration",
    castingTime: "Action",
    range: "Perso",
    components: { verbal: true, somatic: true, material: null },
    duration: "Concentration, jusqu'à 1 minute",
    concentration: true,
    ritual: false,
    classLists: ["bard", "sorcerer", "warlock", "wizard"],
    damage: null,
    description: "Chaque fois qu'une créature vous attaque avant la fin du sort, l'attaquant soustrait 1d4 à son jet d'attaque.",
  },
  {
    key: "bless",
    name: "Bénédiction",
    level: 1,
    school: "enchantment",
    castingTime: "Action",
    range: "9 m",
    components: { verbal: true, somatic: true, material: "un symbole sacré d'une valeur minimale de 5 po" },
    duration: "Concentration, jusqu'à 1 minute",
    concentration: true,
    ritual: false,
    classLists: ["cleric", "paladin"],
    damage: null,
    description: "Vous bénissez jusqu'à trois créatures à portée. Chaque fois qu'une cible effectue un jet d'attaque ou de sauvegarde avant la fin du sort, elle ajoute 1d4 à son jet d'attaque ou de sauvegarde.",
  },
  {
    key: "burning-hands",
    name: "Mains brûlantes",
    level: 1,
    school: "evocation",
    castingTime: "Action",
    range: "Perso",
    components: { verbal: true, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["sorcerer", "wizard"],
    damage: { dice: "3d6", type: "fire", attackRoll: false, save: { ability: "dexterity", onSuccess: "half" } },
    description: "Une fine nappe de flammes jaillit de vous. Toute créature dans un Cône de 4,50 mètres effectue un jet de sauvegarde de Dextérité, subissant 3d6 dégâts de feu en cas d'échec, ou la moitié de ces dégâts en cas de réussite. Les objets inflammables dans le Cône qui ne sont pas portés commencent à brûler.",
  },
  {
    key: "charm-person",
    name: "Charme-personne",
    level: 1,
    school: "enchantment",
    castingTime: "Action",
    range: "9 m",
    components: { verbal: true, somatic: true, material: null },
    duration: "1 heure",
    concentration: false,
    ritual: false,
    classLists: ["bard", "druid", "sorcerer", "warlock", "wizard"],
    damage: null,
    description: "Un humanoïde que vous pouvez voir à portée effectue un jet de sauvegarde de Sagesse. Il le fait avec un Avantage si vous ou vos alliés le combattez. En cas d'échec, la cible subit l'état Charmé jusqu'à la fin du sort ou jusqu'à ce que vous ou vos alliés lui infligiez des dégâts. La créature charmée est amicale envers vous. À la fin du sort, la cible sait que vous l'avez charmée.",
  },
  {
    key: "chill-touch",
    name: "Contact glacial",
    level: 0,
    school: "necromancy",
    castingTime: "Action",
    range: "Contact",
    components: { verbal: true, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["sorcerer", "warlock", "wizard"],
    damage: { dice: "1d10", type: "necrotic", attackRoll: true, save: null },
    description: "Canalisant le froid de la tombe, effectuez une attaque de corps à corps avec un sort contre une cible à portée. Si l'attaque touche, la cible subit 1d10 dégâts nécrotiques et ne peut pas regagner de points de vie avant la fin de votre prochain tour. Amélioration de sort mineur. Les dégâts augmentent de 1d10 lorsque vous atteignez les niveaux 5 (2d10), 11 (3d10) et 17 (4d10).",
  },
  {
    key: "chromatic-orb",
    name: "Orbe chromatique",
    level: 1,
    school: "evocation",
    castingTime: "Action",
    range: "27 m",
    components: { verbal: true, somatic: true, material: "un diamant d'une valeur minimale de 50 po" },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["sorcerer", "wizard"],
    damage: null,
    description: "Vous lancez un orbe d'énergie sur une cible à portée. Choisissez acide, froid, feu, foudre, poison ou tonnerre comme type d'orbe, puis effectuez une attaque de sort à distance contre la cible. Si l'attaque touche, la cible subit 3d8 dégâts du type choisi. Si vous obtenez le même résultat sur deux d8 ou plus, l'orbe bondit vers une autre cible de votre choix dans un rayon de 9 mètres de la cible. Effectuez un jet d'attaque contre la nouvelle cible, puis un nouveau jet de dégâts. L'orbe ne peut pas bondir à nouveau, sauf si vous lancez le sort avec un emplacement de sort de niveau 2 ou supérieur.",
  },
  {
    key: "color-spray",
    name: "Couleurs dansantes",
    level: 1,
    school: "illusion",
    castingTime: "Action",
    range: "Perso",
    components: { verbal: true, somatic: true, material: "une pincée de sable coloré" },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["bard", "sorcerer", "wizard"],
    damage: null,
    description: "Vous lancez un faisceau éblouissant de lumières scintillantes et colorées. Toute créature dans un Cône de 4,50 mètres émanant de vous doit réussir un jet de sauvegarde de Constitution ou subir l'état Aveuglé jusqu'à la fin de votre prochain tour.",
  },
  {
    key: "command",
    name: "Injonction",
    level: 1,
    school: "enchantment",
    castingTime: "Action",
    range: "18 m",
    components: { verbal: true, somatic: false, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["bard", "cleric", "paladin"],
    damage: null,
    description: "Vous donnez un ordre d'un seul mot à une créature que vous pouvez voir à portée. La cible doit réussir un jet de sauvegarde de Sagesse ou suivre l'ordre à son prochain tour. Choisissez l'ordre parmi ces options : Approche. La cible se dirige vers vous par le chemin le plus court et le plus direct, mettant fin à son tour si elle se trouve à 1,50 mètre ou moins de vous. Lâche. La cible laisse tomber ce qu'elle tient et termine son tour. Fuis. La cible passe son tour à s'éloigner de vous par le moyen le plus rapide. Rampe. La cible a l'état À terre et termine son tour. Halte. À son tour, la cible ne bouge pas et n'effectue aucune action ni action Bonus.",
  },
  {
    key: "compelled-duel",
    name: "Duel forcé",
    level: 1,
    school: "enchantment",
    castingTime: "Action bonus",
    range: "9 m",
    components: { verbal: true, somatic: false, material: null },
    duration: "Concentration, jusqu'à 1 minute",
    concentration: true,
    ritual: false,
    classLists: ["paladin"],
    damage: null,
    description: "Vous tentez de forcer une créature à se battre en duel. Une créature que vous pouvez voir à portée effectue un jet de sauvegarde de Sagesse. En cas d'échec, la cible subit un Désavantage aux jets d'attaque contre d'autres créatures que vous, et ne peut pas se déplacer volontairement vers une case située à plus de 9 mètres de vous. Le sort prend fin si vous effectuez un jet d'attaque contre une créature autre que la cible, si vous lancez un sort sur un ennemi autre que la cible, si un de vos alliés inflige des dégâts à la cible ou si vous terminez votre tour à plus de 9 mètres de la cible.",
  },
  {
    key: "comprehend-languages",
    name: "Compréhension des langues",
    level: 1,
    school: "divination",
    castingTime: "Action ou Rituel",
    range: "Perso",
    components: { verbal: true, somatic: true, material: "une pincée de suie et de sel" },
    duration: "1 heure",
    concentration: false,
    ritual: true,
    classLists: ["bard", "sorcerer", "warlock", "wizard"],
    damage: null,
    description: "Pendant toute la durée du sort, vous comprenez le sens littéral de toute langue que vous entendez ainsi que le langage des signes. Vous comprenez également toute langue écrite que vous voyez, mais vous devez toucher la surface sur laquelle les mots sont écrits. Il faut environ une minute pour lire une page de texte. Ce sort ne décode pas les symboles ni les messages secrets.",
  },
  {
    key: "create-or-destroy-water",
    name: "Création ou destruction d'eau",
    level: 1,
    school: "transmutation",
    castingTime: "Action",
    range: "9 m",
    components: { verbal: true, somatic: true, material: "un mélange d'eau et de sable" },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["cleric", "druid"],
    damage: null,
    description: "Vous effectuez l'une des actions suivantes : Création d'eau. Vous créez jusqu'à 40 litres d'eau propre à portée dans un récipient ouvert. L'eau peut aussi tomber sous forme de pluie dans un Cube de 9 mètres de côté à portée, éteignant les flammes. Destruction d'eau. Vous détruisez jusqu'à 40 litres d'eau dans un récipient ouvert à portée. Vous pouvez aussi détruire le brouillard dans un Cube de 9 mètres ce côté à portée.",
  },
  {
    key: "cure-wounds",
    name: "Soins",
    level: 1,
    school: "abjuration",
    castingTime: "Action",
    range: "Contact",
    components: { verbal: true, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["bard", "cleric", "druid", "paladin", "ranger"],
    damage: null,
    description: "Une créature que vous touchez récupère un nombre de points de vie égal à 2d8 plus le modificateur de votre caractéristique d'incantation.",
  },
  {
    key: "dancing-lights",
    name: "Lumières dansantes",
    level: 0,
    school: "illusion",
    castingTime: "Action",
    range: "36 m",
    components: { verbal: true, somatic: true, material: "un peu de phosphore" },
    duration: "Concentration, jusqu'à 1 minute",
    concentration: true,
    ritual: false,
    classLists: ["bard", "sorcerer", "wizard"],
    damage: null,
    description: "Vous créez jusqu'à quatre lumières de la taille d'une torche à portée, les faisant apparaître comme des torches, des lanternes ou des orbes lumineuses flottant pendant la durée du sort. Vous pouvez également combiner les quatre lumières pour former une silhouette de taille M vaguement humaine. Quelle que soit la forme choisie, chaque lumière diffuse une Lumière faible sur un rayon de 3 mètres. Par une action Bonus, vous pouvez déplacer les lumières jusqu'à 18 mètres vers un espace à portée. Une lumière doit se trouver à 6 mètres ou moins d'une autre lumière créée par ce sort. Elle disparaît si elle dépasse la portée du sort.",
  },
  {
    key: "detect-evil-and-good",
    name: "Détection du mal et du bien",
    level: 1,
    school: "divination",
    castingTime: "Action",
    range: "Perso",
    components: { verbal: true, somatic: true, material: null },
    duration: "Concentration, jusqu'à 10 minutes",
    concentration: true,
    ritual: false,
    classLists: ["cleric", "paladin"],
    damage: null,
    description: "Pendant la durée du sort, vous détectez l'emplacement de toute aberration, céleste, élémentaire, fée, fiélon ou mort-vivant dans un rayon de 9 mètres autour de vous. Vous détectez également si le sort sanctification est actif par ici et, si oui, où. Le sort est bloqué par 30 cm de pierre, de terre ou de bois, par 2,50 cm de métal, ou par une fine feuille de plomb.",
  },
  {
    key: "detect-magic",
    name: "Détection de la magie",
    level: 1,
    school: "divination",
    castingTime: "Action ou Rituel",
    range: "Perso",
    components: { verbal: true, somatic: true, material: null },
    duration: "Concentration, jusqu'à 10 minutes",
    concentration: true,
    ritual: true,
    classLists: ["bard", "cleric", "druid", "paladin", "ranger", "sorcerer", "warlock", "wizard"],
    damage: null,
    description: "Pendant la durée du sort, vous ressentez la présence d'effets magiques dans un rayon de 9 mètres autour de vous. Si vous ressentez ces effets, vous pouvez utiliser l'action Magie pour voir une faible aura autour de toute créature ou objet visible dans la zone qui porte la magie. Si un effet a été créé par un sort, vous connaissez l'école de magie du sort. Le sort est bloqué par 30 cm de pierre, de terre ou de bois, par 2,50 cm de métal, ou par une fine feuille de plomb.",
  },
  {
    key: "detect-poison-and-disease",
    name: "Détection du poison et des maladies",
    level: 1,
    school: "divination",
    castingTime: "Action ou Rituel",
    range: "Perso",
    components: { verbal: true, somatic: true, material: "une feuille d'if" },
    duration: "Concentration, jusqu'à 10 minutes",
    concentration: true,
    ritual: true,
    classLists: ["cleric", "druid", "paladin", "ranger"],
    damage: null,
    description: "Pendant la durée du sort, vous détectez l'emplacement des poisons, des créatures venimeuses ou toxiques, et des contagions magiques dans un rayon de 9 mètres autour de vous. Vous détectez le type de poison, de créature ou de contagion dans chaque cas. Le sort est bloqué par 30 cm de pierre, de terre ou de bois, par 2,50 cm de métal, ou par une fine feuille de plomb.",
  },
  {
    key: "disguise-self",
    name: "Déguisement",
    level: 1,
    school: "illusion",
    castingTime: "Action",
    range: "Perso",
    components: { verbal: true, somatic: true, material: null },
    duration: "1 heure",
    concentration: false,
    ritual: false,
    classLists: ["bard", "sorcerer", "wizard"],
    damage: null,
    description: "Vous vous transformez (vêtements, armure, armes et autres effets personnels inclus) jusqu'à la fin du sort. Vous pouvez paraître plus petit ou plus grand de 30 cm, et paraître plus lourd ou plus léger. Vous devez adopter une forme dont la disposition des membres est identique à la vôtre. Mis à part cela, l'ampleur de l'illusion dépend de vous. Les changements apportés par ce sort ne résistent pas à une inspection physique. Par exemple, si vous utilisez ce sort pour ajouter un chapeau à votre tenue, les objets le traversent et quiconque le touche ne ressent rien. Pour discerner que vous êtes déguisé, une créature doit prendre l'action Étude pour inspecter votre apparence et réussir un jet d'Intelligence (Investigation) contre le DD de sauvegarde de votre sort.",
  },
  {
    key: "dissonant-whispers",
    name: "Murmures dissonants",
    level: 1,
    school: "enchantment",
    castingTime: "Action",
    range: "18 m",
    components: { verbal: true, somatic: false, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["bard"],
    damage: { dice: "3d6", type: "psychic", attackRoll: false, save: { ability: "wisdom", onSuccess: "half" } },
    description: "Une créature de votre choix que vous pouvez voir portée entend une mélodie discordante dans son esprit. La cible effectue un jet de sauvegarde de Sagesse. En cas d'échec, elle subit 3d6 dégâts psychiques et doit immédiatement utiliser sa Réaction, si elle en a une, pour s'éloigner le plus loin possible de vous, en empruntant le chemin le plus sûr. En cas de réussite, la cible subit seulement la moitié des dégâts.",
  },
  {
    key: "divine-favor",
    name: "Faveur divine",
    level: 1,
    school: "transmutation",
    castingTime: "Action bonus",
    range: "Perso",
    components: { verbal: true, somatic: true, material: null },
    duration: "1 minute",
    concentration: false,
    ritual: false,
    classLists: ["paladin"],
    damage: null,
    description: "Jusqu'à la fin du sort, vos attaques avec des armes infligent 1d4 dégâts radiants supplémentaires si vous touchez.",
  },
  {
    key: "divine-smite",
    name: "Châtiment divin",
    level: 1,
    school: "evocation",
    castingTime: "Action bonus",
    range: "Perso",
    components: { verbal: true, somatic: false, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["paladin"],
    damage: { dice: "2d8", type: "radiant", attackRoll: true, save: null },
    description: "La cible subit 2d8 dégâts radiants supplémentaires suite à l'attaque. Les dégâts augmentent de 1d8 si la cible est un fiélon ou un mort-vivant.",
  },
  {
    key: "druidcraft",
    name: "Druidisme",
    level: 0,
    school: "transmutation",
    castingTime: "Action",
    range: "9 m",
    components: { verbal: true, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["druid"],
    damage: null,
    description: "En chuchotant aux esprits de la nature, vous créez l'un des effets suivants à portée. Capteur climatique. Vous créez un effet sensoriel inoffensif de taille TP qui prédit le temps qu'il fera à votre emplacement pour les prochaines 24 heures. Cet effet peut se manifester par un orbe doré pour un ciel dégagé, un nuage pour la pluie, des flocons de neige pour la neige, etc. Cet effet persiste pendant 1 round. Floraison. Vous faites instantanément éclore une fleur, ouvrir une gousse ou éclore un bourgeon. Effet sensoriel. Vous créez un effet sensoriel inoffensif, comme des feuilles qui tombent, des fées dansantes spectrales, une légère brise, le bruit d'un animal ou la faible odeur d'une mouffette. L'effet doit tenir dans un Cube de 1,50 mètre de côté. Jeu avec le feu. Vous allumez ou éteignez une bougie, une torche ou un feu de camp.",
  },
  {
    key: "eldritch-blast",
    name: "Décharge occulte",
    level: 0,
    school: "evocation",
    castingTime: "Action",
    range: "36 m",
    components: { verbal: true, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["warlock"],
    damage: { dice: "1d10", type: "force", attackRoll: true, save: null },
    description: "Vous lancez un rayon d'énergie crépitante. Effectuez une attaque à distance contre une créature ou un objet à portée. Si l'attaque touche, la cible subit 1d10 dégâts de force. Amélioration de sort mineur. Le sort crée deux rayons au niveau 5, trois au niveau 11 et quatre au niveau 17. Vous pouvez diriger les rayons vers une même cible ou vers des cibles différentes. Effectuez un jet d'attaque distinct pour chaque rayon.",
  },
  {
    key: "elementalism",
    name: "Élémentalisme",
    level: 0,
    school: "transmutation",
    castingTime: "Action",
    range: "9 m",
    components: { verbal: true, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["druid", "sorcerer", "wizard"],
    damage: null,
    description: "Vous avez un contrôle sur les éléments, produisant un des effets suivants, dans les limites de la portée : Appel d'air. Vous créez une brise assez forte pour faire onduler du tissu, soulever la poussière, faire bruisser les feuilles d'un arbre et fermer une porte ouverte ou des volets, dans un Cube de 1,50 mètre de côté. Appel de terre. Vous créez un fin voile de poussière ou de sable qui recouvre les surfaces dans une zone de 1,50 mètre de côté. Ou sinon, vous pouvez faire apparaitre un seul mot, avec votre écriture, dans la terre ou le sable. Appel de feu. Vous créez un fin nuage composé de braises et de fumée colorée et parfumée (mais inoffensive) dans un Cube de 1,50 mètre de côté. Vous choisissez la couleur et l'odeur de la fumée, et les braises peuvent allumer bougies, torches et lampes dans la zone du sort. L'odeur de la fumée persiste pendant 1 minute. Appel d'eau. Vous créez une bruine de brume fraiche qui humidifie légèrement les créatures et les objets dans un Cube de 1,50 mètre de côté. Vous pouvez aussi choisir de créer 20 cl d'eau potable, soit dans un récipient ouvert, soit au sol. L'eau ainsi créée s'évapore en 1 minute. Façonnage élémentaire. Vous utilisez la poussière, le sable, le feu, la fumée, la brume ou l'eau qui tiennent dans un Cube de 30 cm de côté pour former une forme grossière (comme celle d'une créature ou d'un objet) pour 1 heure.",
  },
  {
    key: "ensnaring-strike",
    name: "Frappe piégeuse",
    level: 1,
    school: "conjuration",
    castingTime: "Action bonus",
    range: "Perso",
    components: { verbal: true, somatic: false, material: null },
    duration: "Concentration, jusqu'à 1 minute",
    concentration: true,
    ritual: false,
    classLists: ["ranger"],
    damage: null,
    description: "Lorsque vous touchez la cible, des lianes avides apparaissent sur elle. Elle effectue alors un jet de sauvegarde de Force. Une créature de taille G ou supérieure bénéficie d'un Avantage pour ce jet de sauvegarde. En cas d'échec, la cible subit l'état Entravé jusqu'à la fin du sort. En cas de réussite, les lianes se dessèchent et le sort prend fin. Tant qu'elle est entravée, la cible subit 1d6 dégâts perforants au début de chacun de ses tours. La cible ou une créature à sa portée peut prendre une action pour effectuer un jet de Force (Athlétisme) contre le DD de sauvegarde de votre sort. En cas de réussite, le sort prend fin.",
  },
  {
    key: "entangle",
    name: "Enchevêtrement",
    level: 1,
    school: "conjuration",
    castingTime: "Action",
    range: "27 m",
    components: { verbal: true, somatic: true, material: null },
    duration: "Concentration, jusqu'à 1 minute",
    concentration: true,
    ritual: false,
    classLists: ["druid", "ranger"],
    damage: null,
    description: "Des plantes agrippantes surgissent du sol dans un carré de 6 mètres de côté à portée. Pendant la durée du sort, ces plantes transforment le sol de la zone en Terrain difficile. Elles disparaissent à la fin du sort. Toute créature (autre que vous) présente dans la zone au moment du lancement du sort doit réussir un jet de sauvegarde de Force ou subir l'état Entravé jusqu'à la fin du sort. Une créature entravée peut effectuer un jet de Force (Athlétisme) contre le DD de sauvegarde de votre sort. En cas de réussite, elle se libère des plantes agrippantes et n'est plus entravée par elles.",
  },
  {
    key: "expeditious-retreat",
    name: "Repli expéditif",
    level: 1,
    school: "transmutation",
    castingTime: "Action bonus",
    range: "Perso",
    components: { verbal: true, somatic: true, material: null },
    duration: "Concentration, jusqu'à 10 minutes",
    concentration: true,
    ritual: false,
    classLists: ["sorcerer", "warlock", "wizard"],
    damage: null,
    description: "Vous prenez l'action Pointe et, jusqu'à la fin du sort, vous pouvez prendre de nouveau cette action en tant qu'action Bonus.",
  },
  {
    key: "faerie-fire",
    name: "Lueurs féeriques",
    level: 1,
    school: "evocation",
    castingTime: "Action",
    range: "18 m",
    components: { verbal: true, somatic: false, material: null },
    duration: "Concentration, jusqu'à 1 minute",
    concentration: true,
    ritual: false,
    classLists: ["bard", "druid"],
    damage: null,
    description: "Les objets situés dans un Cube de 6 mètres de côté à portée sont entourés d'une lumière bleue, verte ou violette (selon votre choix). Toute créature présente dans le Cube est également délimitée si elle rate un jet de sauvegarde de Dextérité. Pendant la durée du sort, les objets et les créatures affectées émettent une Lumière faible sur un rayon de 3 mètres et ne peuvent pas bénéficier de l'état Invisible. Les jets d'attaque contre une créature ou un objet affecté ont un Avantage si l'attaquant peut le voir.",
  },
  {
    key: "false-life",
    name: "Simulacre de vie",
    level: 1,
    school: "necromancy",
    castingTime: "Action",
    range: "Perso",
    components: { verbal: true, somatic: true, material: "une goutte d'alcool" },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["sorcerer", "wizard"],
    damage: null,
    description: "Vous gagnez 2d4 + 4 points de vie temporaires.",
  },
  {
    key: "feather-fall",
    name: "Feuille morte",
    level: 1,
    school: "transmutation",
    castingTime: "Réaction",
    range: "18 m",
    components: { verbal: true, somatic: false, material: "une petite plume ou un peu de duvet" },
    duration: "1 minute",
    concentration: false,
    ritual: false,
    classLists: ["bard", "sorcerer", "wizard"],
    damage: null,
    description: "Choisissez jusqu'à cinq créatures à portée qui sont en chute libre. La vitesse de chute d'une créature est réduite à 18 mètres par round jusqu'à la fin du sort. Si une créature atterrit avant la fin du sort, elle ne subit aucun dégât de la chute et le sort prend fin pour elle.",
  },
  {
    key: "find-familiar",
    name: "Appel de familier",
    level: 1,
    school: "conjuration",
    castingTime: "1 heure ou Rituel",
    range: "3 m",
    components: { verbal: true, somatic: true, material: "de l'encens qui brûle d'une valeur minimale de 10 po, que le sort consomme" },
    duration: "Instantanée",
    concentration: false,
    ritual: true,
    classLists: ["wizard"],
    damage: null,
    description: "Vous obtenez les services d'un familier, un esprit qui prend une forme animale de votre choix : chauve-souris, chat, grenouille, faucon, lézard, pieuvre, chouette, rat, corbeau, araignée, belette ou autre Bête dont le FP est de 0. Il apparait dans une case libre à portée et possède le profil de la forme choisie, mais est du type Céleste, Fée ou Fiélon (selon votre choix) au lieu de Bête. Votre familier agit indépendamment de vous, mais obéit à vos ordres. Lien télépathique. Tant que votre familier est dans un rayon de 30 mètres autour de vous, vous pouvez communiquer avec lui par télépathie. De plus, par une action Bonus, vous pouvez voir à travers les yeux du familier et entendre ce qu'il entend jusqu'au début de votre prochain tour, bénéficiant ainsi des avantages de ses sens spéciaux. Enfin, lorsque vous lancez un sort dont la portée est de contact, votre familier peut appliquer le contact. Votre familier doit se trouver dans un rayon de 30 mètres et doit prendre une Réaction pour appliquer le contact lorsque vous lancez le sort. Combat. Le familier est votre allié et celui de vos alliés. Il lance sa propre Initiative et agit à son tour. Un familier ne peut pas attaquer mais peut effectuer d'autres actions normalement. Disparition du familier. Lorsque le familier tombe à 0 point de vie, il disparaît. Il réapparaît si vous lancez ce sort à nouveau. Par une action Magie, vous pouvez renvoyer temporairement le familier dans une niche dimensionnelle. Vous pouvez également le renvoyer définitivement. Par une action Magie, tant qu'il est temporairement renvoyé, vous pouvez le faire réapparaître dans un espace inoccupé dans un rayon de 9 mètres. Chaque fois que le familier tombe à 0 point de vie ou disparaît dans la niche dimensionnelle, il laisse derrière lui tout ce qu'il portait. Un seul familier. Vous ne pouvez pas avoir plus d'un familier à la fois. Si vous lancez ce sort alors que vous avez un familier, il adopte une nouvelle forme valide.",
  },
  {
    key: "fire-bolt",
    name: "Trait de feu",
    level: 0,
    school: "evocation",
    castingTime: "Action",
    range: "36 m",
    components: { verbal: true, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["sorcerer", "wizard"],
    damage: { dice: "1d10", type: "fire", attackRoll: true, save: null },
    description: "Vous lancez une particule de feu sur une créature ou un objet à portée. Effectuez une attaque de sort à distance contre la cible. Si l'attaque touche, la cible subit 1d10 dégâts de feu. Un objet inflammable touché par ce sort commence à brûler s'il n'est pas porté. Amélioration de sort mineur. Les dégâts augmentent de 1d10 lorsque vous atteignez les niveaux 5 (2d10), 11 (3d10) et 17 (4d10).",
  },
  {
    key: "fog-cloud",
    name: "Nappe de brouillard",
    level: 1,
    school: "conjuration",
    castingTime: "Action",
    range: "36 m",
    components: { verbal: true, somatic: true, material: null },
    duration: "Concentration, jusqu'à 1 heure",
    concentration: true,
    ritual: false,
    classLists: ["druid", "ranger", "sorcerer", "wizard"],
    damage: null,
    description: "Vous créez une Sphère de brouillard de 6 mètres de rayon centrée sur un point à portée. La Sphère est une zone de Visibilité nulle. Elle se maintient pendant toute la durée du sort ou jusqu'à ce qu'un vent fort (comme celui créé par bourrasque) la disperse.",
  },
  {
    key: "friends",
    name: "Amis|Faux amis",
    level: 0,
    school: "enchantment",
    castingTime: "Action",
    range: "3 m",
    components: { verbal: false, somatic: true, material: "un peu de maquillage" },
    duration: "Concentration, jusqu'à 1 minute",
    concentration: true,
    ritual: false,
    classLists: ["bard", "sorcerer", "warlock", "wizard"],
    damage: null,
    description: "Vous émettez magiquement un sentiment d'amitié envers une créature que vous pouvez voir à portée. La cible doit réussir un jet de sauvegarde de Sagesse ou subir l'état Charmé pendant toute la durée du sort. La cible réussit automatiquement si elle n'est pas humanoïde, si vous la combattez ou si vous avez lancé ce sort sur elle au cours des dernières 24 heures. Le sort prend fin prématurément si la cible subit des dégâts, si vous effectuez un jet d'attaque, infligez des dégâts ou forcez quelqu'un à effectuer un jet de sauvegarde. À la fin du sort, la cible sait que vous l'avez charmée.",
  },
  {
    key: "goodberry",
    name: "Baies nourricières",
    level: 1,
    school: "conjuration",
    castingTime: "Action",
    range: "Perso",
    components: { verbal: true, somatic: true, material: "une branche de gui" },
    duration: "24 heures",
    concentration: false,
    ritual: false,
    classLists: ["druid", "ranger"],
    damage: null,
    description: "Dix baies imprégnées de magie pendant toute la durée du sort apparaissent dans votre main. Une créature peut prendre une action Bonus pour en manger une. Manger une baie restaure 1 point de vie et fournit suffisamment de nourriture pour nourrir une créature pendant une journée. Les baies non consommées disparaissent à la fin du sort.",
  },
  {
    key: "grease",
    name: "Graisse",
    level: 1,
    school: "conjuration",
    castingTime: "Action",
    range: "18 m",
    components: { verbal: true, somatic: true, material: "un peu de couenne de porc ou de beurre" },
    duration: "1 minute",
    concentration: false,
    ritual: false,
    classLists: ["sorcerer", "wizard"],
    damage: null,
    description: "De la graisse ininflammable recouvre le sol sur une surface carrée de 3 mètres de côté centrée sur un point à portée et le transforme en Terrain difficile pendant toute la durée du sort. Lorsque la graisse apparaît, toute créature se trouvant dans sa zone doit réussir un jet de sauvegarde de Dextérité ou subir l'état À terre. Une créature qui entre dans la zone ou y termine son tour doit également réussir ce jet de sauvegarde ou subir l'état À terre.",
  },
  {
    key: "guidance",
    name: "Assistance",
    level: 0,
    school: "divination",
    castingTime: "Action",
    range: "Contact",
    components: { verbal: true, somatic: true, material: null },
    duration: "Concentration, jusqu'à 1 minute",
    concentration: true,
    ritual: false,
    classLists: ["cleric", "druid"],
    damage: null,
    description: "Vous touchez une créature consentante et choisissez une compétence. Jusqu'à la fin du sort, la créature ajoute 1d4 à tout jet de caractéristique utilisant la compétence choisie.",
  },
  {
    key: "guiding-bolt",
    name: "Rayon traçant",
    level: 1,
    school: "evocation",
    castingTime: "Action",
    range: "36 m",
    components: { verbal: true, somatic: true, material: null },
    duration: "1 round",
    concentration: false,
    ritual: false,
    classLists: ["cleric"],
    damage: { dice: "4d6", type: "radiant", attackRoll: true, save: null },
    description: "Vous lancez un éclair de lumière vers une créature à portée. Effectuez une attaque de sort à distance contre la cible. Si l'attaque touche, elle subit 4d6 dégâts radiants et le prochain jet d'attaque effectué contre elle avant la fin de votre prochain tour bénéficie d'un Avantage.",
  },
  {
    key: "hail-of-thorns",
    name: "Grêle d'épines",
    level: 1,
    school: "conjuration",
    castingTime: "Action bonus",
    range: "Perso",
    components: { verbal: true, somatic: false, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["ranger"],
    damage: { dice: "1d10", type: "piercing", attackRoll: false, save: { ability: "dexterity", onSuccess: "half" } },
    description: "Lorsque vous touchez la créature, ce sort crée une pluie d'épines qui jaillit de votre arme à distance ou de vos munitions. La cible de l'attaque et toute créature dans un rayon de 1,50 mètre autour d'elle effectuent un jet de sauvegarde de Dextérité, subissant 1d10 dégâts perforants en cas d'échec ou la moitié de ces dégâts en cas de réussite.",
  },
  {
    key: "healing-word",
    name: "Mot de guérison",
    level: 1,
    school: "abjuration",
    castingTime: "Action bonus",
    range: "18 m",
    components: { verbal: true, somatic: false, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["bard", "cleric", "druid"],
    damage: null,
    description: "Une créature de votre choix que vous pouvez voir à portée récupère 2d4 points de vie plus le modificateur de votre caractéristique d'incantation.",
  },
  {
    key: "hellish-rebuke",
    name: "Représailles infernales",
    level: 1,
    school: "evocation",
    castingTime: "Réaction",
    range: "18 m",
    components: { verbal: true, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["warlock"],
    damage: { dice: "2d10", type: "fire", attackRoll: false, save: { ability: "dexterity", onSuccess: "half" } },
    description: "La créature qui vous a blessé est momentanément entourée de flammes vertes. Elle effectue un jet de sauvegarde de Dextérité et subit 2d10 dégâts de feu en cas d'échec, ou la moitié en cas de réussite.",
  },
  {
    key: "heroism",
    name: "Héroïsme",
    level: 1,
    school: "enchantment",
    castingTime: "Action",
    range: "Contact",
    components: { verbal: true, somatic: true, material: null },
    duration: "Concentration, jusqu'à 1 minute",
    concentration: true,
    ritual: false,
    classLists: ["bard", "paladin"],
    damage: null,
    description: "Une créature consentante que vous touchez est imprégnée de bravoure. Jusqu'à la fin du sort, elle est immunisée contre l'état Effrayé et gagne des points de vie temporaires égaux au modificateur de votre caractéristique d'incantation au début de chacun de ses tours.",
  },
  {
    key: "hex",
    name: "Maléfice",
    level: 1,
    school: "enchantment",
    castingTime: "Action bonus",
    range: "27 m",
    components: { verbal: true, somatic: true, material: "un oeil pétrifié de triton" },
    duration: "Concentration, jusqu'à 1 heure",
    concentration: true,
    ritual: false,
    classLists: ["warlock"],
    damage: null,
    description: "Vous jetez une malédiction sur une créature que vous pouvez voir à portée. Jusqu'à la fin du sort, vous infligez 1d6 dégâts nécrotiques supplémentaires à la cible à chaque jet d'attaque. Choisissez également une caractéristique lorsque vous lancez le sort. La cible subit un désavantage aux jets de caractéristique effectués avec la caractéristique choisie. Si la cible tombe à 0 point de vie avant la fin du sort, vous pouvez utiliser une action Bonus lors d'un tour ultérieur pour maudire une nouvelle créature.",
  },
  {
    key: "hunter-s-mark",
    name: "Marque du chasseur",
    level: 1,
    school: "divination",
    castingTime: "Action bonus",
    range: "27 m",
    components: { verbal: true, somatic: false, material: null },
    duration: "Concentration, jusqu'à 1 heure",
    concentration: true,
    ritual: false,
    classLists: ["ranger"],
    damage: null,
    description: "Vous marquez magiquement une créature que vous pouvez voir à portée comme votre proie. Jusqu'à la fin du sort, vous infligez 1d6 points de dégâts de force supplémentaires à la cible pour chaque jet d'attaque réussi. Vous bénéficiez également d'un Avantage à tout jet de Sagesse (Perception ou Survie) effectué pour la trouver. Si la cible tombe à 0 point de vie avant la fin du sort, vous pouvez utiliser une action Bonus pour marquer une nouvelle créature que vous pouvez voir à portée.",
  },
  {
    key: "ice-knife",
    name: "Couteau de glace",
    level: 1,
    school: "conjuration",
    castingTime: "Action",
    range: "18 m",
    components: { verbal: false, somatic: true, material: "une goutte d'eau et un morceau de glace" },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["druid", "sorcerer", "wizard"],
    damage: { dice: "1d10", type: "piercing", attackRoll: true, save: null },
    description: "Vous créez un éclat de glace et le lancez sur une créature à portée. Effectuez une attaque de sort à distance contre la cible. Si l'attaque touche, la cible subit 1d10 dégâts perforants. Que l'attaque soit réussie ou non, l'éclat explose. La cible et tout créature dans un rayon de 1,50 mètre doivent réussir un jet de sauvegarde de Dextérité ou subir 2d6 dégâts de froid.",
  },
  {
    key: "identify",
    name: "Identification",
    level: 1,
    school: "divination",
    castingTime: "1 minute ou Rituel",
    range: "Contact",
    components: { verbal: true, somatic: true, material: "une perle d'une valeur minimale de 100 po" },
    duration: "Instantanée",
    concentration: false,
    ritual: true,
    classLists: ["bard", "wizard"],
    damage: null,
    description: "Vous touchez un objet pendant l'incantation du sort. S'il s'agit d'un objet magique, vous connaissez ses propriétés et son utilisation, si un lien est nécessaire et combien de charges il possède, le cas échéant. Vous savez si des sorts en cours affectent l'objet et lesquels. Si l'objet a été créé par un sort, vous connaissez le nom de ce sort. Si par contre vous touchez une créature pendant l'incantation, vous savez quels sorts l'affectent, le cas échéant.",
  },
  {
    key: "illusory-script",
    name: "Texte illusoire",
    level: 1,
    school: "illusion",
    castingTime: "1 minute ou Rituel",
    range: "Contact",
    components: { verbal: false, somatic: true, material: "de l'encre d'une valeur minimale de 10 po, que le sort consomme" },
    duration: "10 jours",
    concentration: false,
    ritual: true,
    classLists: ["bard", "warlock", "wizard"],
    damage: null,
    description: "Vous écrivez sur du parchemin, du papier ou un autre support approprié et l'imprégnez d'une illusion qui dure toute la durée du sort. Pour vous et les créatures que vous désignez lors du lancement du sort, l'écriture paraît normale, semble écrite de votre main et transmet le sens que vous aviez prévu. Pour tous les autres, l'écriture apparaît comme étant d'un alphabet inconnu ou magique, et est inintelligible. L'illusion peut également altérer le sens, l'écriture et la langue du texte, à condition que cette langue soit connue. Si le sort est dissipé, l'écriture originale et l'illusion disparaissent. Une créature dotée de Vision véritable peut lire le message caché.",
  },
  {
    key: "inflict-wounds",
    name: "Blessure",
    level: 1,
    school: "necromancy",
    castingTime: "Action",
    range: "Contact",
    components: { verbal: true, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["cleric"],
    damage: { dice: "2d10", type: "necrotic", attackRoll: false, save: { ability: "constitution", onSuccess: "half" } },
    description: "Une créature que vous touchez effectue un jet de sauvegarde de Constitution et subit 2d10 dégâts nécrotiques en cas d'échec, ou la moitié de ces dégâts en cas de réussite.",
  },
  {
    key: "jump",
    name: "Saut",
    level: 1,
    school: "transmutation",
    castingTime: "Action bonus",
    range: "Contact",
    components: { verbal: true, somatic: true, material: "une patte arrière de sauterelle" },
    duration: "1 minute",
    concentration: false,
    ritual: false,
    classLists: ["druid", "ranger", "sorcerer", "wizard"],
    damage: null,
    description: "Vous touchez une créature consentante. Une fois à chacun de ses tours jusqu'à la fin du sort, cette créature peut sauter jusqu'à 9 mètres en dépensant 3 mètres de mouvement.",
  },
  {
    key: "light",
    name: "Lumière",
    level: 0,
    school: "evocation",
    castingTime: "Action",
    range: "Contact",
    components: { verbal: true, somatic: false, material: "une luciole ou de la mousse phosphorescente" },
    duration: "1 heure",
    concentration: false,
    ritual: false,
    classLists: ["bard", "cleric", "sorcerer", "wizard"],
    damage: null,
    description: "Vous touchez un objet de taille G ou inférieure qui n'est pas porté par quelqu'un d'autre. Jusqu'à la fin du sort, l'objet émet une Lumière vive sur un rayon de 6 mètres et une Lumière faible sur 6 mètres supplémentaires. La lumière peut être colorée à votre guise. Recouvrir l'objet par quelque chose d'opaque bloque la lumière. Le sort prend fin si vous le relancez.",
  },
  {
    key: "longstrider",
    name: "Grande foulée",
    level: 1,
    school: "transmutation",
    castingTime: "Action",
    range: "Contact",
    components: { verbal: true, somatic: true, material: "une pincée de terre" },
    duration: "1 heure",
    concentration: false,
    ritual: false,
    classLists: ["bard", "druid", "ranger", "wizard"],
    damage: null,
    description: "Vous touchez une créature. La Vitesse de la cible augmente de 3 mètres jusqu'à la fin du sort.",
  },
  {
    key: "mage-armor",
    name: "Armure de mage",
    level: 1,
    school: "abjuration",
    castingTime: "Action",
    range: "Contact",
    components: { verbal: true, somatic: true, material: "un morceau de cuir traité" },
    duration: "8 heures",
    concentration: false,
    ritual: false,
    classLists: ["sorcerer", "wizard"],
    damage: null,
    description: "Vous touchez une créature consentante qui ne porte pas d'armure. Jusqu'à la fin du sort, la CA de base de la cible passe à 13, plus son modificateur de Dextérité. Le sort prend fin prématurément si la cible enfile une armure.",
  },
  {
    key: "mage-hand",
    name: "Main de mage",
    level: 0,
    school: "conjuration",
    castingTime: "Action",
    range: "9 m",
    components: { verbal: true, somatic: true, material: null },
    duration: "1 minute",
    concentration: false,
    ritual: false,
    classLists: ["bard", "sorcerer", "warlock", "wizard"],
    damage: null,
    description: "Une main spectrale et flottante apparaît à un endroit que vous choisissez à portée. La main reste active pendant toute la durée du sort. Elle disparaît si elle s'éloigne de vous de plus de 9 mètres ou si vous relancez ce sort. Lorsque vous lancez ce sort, vous pouvez utiliser la main pour manipuler un objet, ouvrir une porte ou un contenant déverrouillé, ranger ou récupérer un objet d'un contenant ouvert, ou vider le contenu d'une fiole. Par une action Magie lors de vos tours ultérieurs, vous pouvez continuer de contrôler la main ainsi. Cette action vous permet de déplacer la main jusqu'à 9 mètres. La main ne peut pas attaquer, ni activer des objets magiques, ni porter plus de 5 kg.",
  },
  {
    key: "magic-missile",
    name: "Projectile magique",
    level: 1,
    school: "evocation",
    castingTime: "Action",
    range: "36 m",
    components: { verbal: true, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["sorcerer", "wizard"],
    damage: { dice: "1d4+1", type: "force", attackRoll: false, save: null },
    description: "Vous créez trois fléchettes lumineuses de force magique. Chaque fléchette touche une créature de votre choix que vous pouvez voir et à portée. Une fléchette inflige 1d4 + 1 point de dégâts de force à sa cible. Les fléchettes frappent toutes simultanément, et vous pouvez les diriger pour toucher une ou plusieurs créatures.",
  },
  {
    key: "mending",
    name: "Réparation",
    level: 0,
    school: "transmutation",
    castingTime: "1 minute",
    range: "Contact",
    components: { verbal: true, somatic: true, material: "deux magnétites" },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["bard", "cleric", "druid", "sorcerer", "wizard"],
    damage: null,
    description: "Ce sort répare une cassure ou une déchirure sur un objet que vous touchez, comme un maillon de chaîne brisé, les deux moitiés d'une clé cassée, une cape déchirée ou une outre qui fuit. Tant que la déchirure ne dépasse pas 30 cm dans une dimension, vous la réparez et ne laissez aucune trace du dommage initial. Ce sort peut réparer physiquement un objet magique, mais il ne peut pas restaurer sa magie.",
  },
  {
    key: "message",
    name: "Message",
    level: 0,
    school: "transmutation",
    castingTime: "Action",
    range: "36 m",
    components: { verbal: false, somatic: true, material: "du fil de cuivre" },
    duration: "1 round",
    concentration: false,
    ritual: false,
    classLists: ["bard", "druid", "sorcerer", "wizard"],
    damage: null,
    description: "Vous pointez une créature à portée et murmurez un message. La cible (et elle seule) entend le message et peut répondre par un murmure que vous seul pouvez entendre. Vous pouvez lancer ce sort à travers des objets solides si vous connaissez la cible et savez qu'elle se trouve au-delà de la barrière. Un silence magique, 30 cm de pierre, de métal ou de bois, ou une fine feuille de plomb bloquent le sort.",
  },
  {
    key: "mind-sliver",
    name: "Piqûre mentale",
    level: 0,
    school: "enchantment",
    castingTime: "Action",
    range: "18 m",
    components: { verbal: true, somatic: false, material: null },
    duration: "1 round",
    concentration: false,
    ritual: false,
    classLists: ["sorcerer", "warlock", "wizard"],
    damage: { dice: "1d6", type: "psychic", attackRoll: false, save: { ability: "intelligence", onSuccess: "none" } },
    description: "Vous essayez de rompre temporairement l'esprit d'une créature que vous pouvez voir à portée. La cible doit réussir un jet de sauvegarde d'Intelligence ou subir 1d6 dégâts psychiques et soustraire 1d4 du prochain jet de sauvegarde qu'elle effectue avant la fin de votre prochain tour. Amélioration de sort mineur. Les dégâts augmentent de 1d6 lorsque vous atteignez les niveaux 5 (2d6), 11 (3d6) et 17 (4d6).",
  },
  {
    key: "minor-illusion",
    name: "Illusion mineure",
    level: 0,
    school: "illusion",
    castingTime: "Action",
    range: "9 m",
    components: { verbal: false, somatic: true, material: "un peu de laine brute" },
    duration: "1 minute",
    concentration: false,
    ritual: false,
    classLists: ["bard", "sorcerer", "warlock", "wizard"],
    damage: null,
    description: "Vous créez un son ou l'image d'un objet, à portée, qui se maintient pendant toute la durée du sort. Voir les descriptions ci-dessous pour les différents effets. L'illusion disparait si vous relancez ce sort. Si une créature entreprend l'action Étudier pour examiner le son ou l'image, elle peut reconnaitre qu'il s'agit d'une illusion en réussissant un jet d'Intelligence (Investigation) contre le DD de sauvegarde de votre sort. Si une créature reconnait ainsi l'illusion pour ce qu'elle est, la perçoit toujours, mais amoindrie. Son. Si vous créez un son, son intensité peut aller du chuchotement au cri. Cela peut être votre voix, la voix de quelqu'un d'autre, un rugissement de lion, un battement de tambour ou tout autre son de votre choix. Le son se poursuit sans faiblir pendant toute la durée du sort, ou vous pouvez choisir de faire différents sons individuels, à différents intervalles, jusqu'à la fin du sort. Image. Si vous créez l'image d'un objet (comme une chaise, des empreintes boueuses ou un petit coffre), cela ne peut pas être plus grand qu'un Cube de 1,50 mètre de côté. L'image ne produit ni son, ni lumière, ni odeur, ni autre effet sensoriel. Interagir physiquement avec l'illusion révèle sa nature, car elle est intangible.",
  },
  {
    key: "poison-spray",
    name: "Bouffée de poison",
    level: 0,
    school: "necromancy",
    castingTime: "Action",
    range: "9 m",
    components: { verbal: true, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["druid", "sorcerer", "warlock", "wizard"],
    damage: { dice: "1d12", type: "poison", attackRoll: true, save: null },
    description: "Vous projetez une brume toxique sur une créature à portée. Effectuez une attaque de sort à distance contre la cible. Si l'attaque touche, la cible subit 1d12 dégâts de poison. Amélioration de sort mineur. Les dégâts augmentent de 1d12 aux niveaux 5 (2d12), 11 (3d12) et 17 (4d12).",
  },
  {
    key: "prestidigitation",
    name: "Prestidigitation",
    level: 0,
    school: "transmutation",
    castingTime: "Action",
    range: "3 m",
    components: { verbal: true, somatic: true, material: null },
    duration: "Jusqu'à 1 heure",
    concentration: false,
    ritual: false,
    classLists: ["bard", "sorcerer", "warlock", "wizard"],
    damage: null,
    description: "Vous créez un effet magique dans la portée du sort. Choisissez l'effet dans les options ci-dessous. Si vous lancez ce sort plusieurs fois, vous pouvez garder actif jusqu'à trois de ses effets non instantanés simultanément. Effet sensoriel. Vous créez instantanément un effet sensoriel inoffensif, comme une pluie d'étincelles, un souffle de vent, des notes de musique tenues ou une odeur étrange. Jeu avec le feu. Vous allumez ou soufflez instantanément une bougie, une torche ou un petit feu de camp. Nettoyage ou maculage. Vous nettoyez ou souillez instantanément un objet ne mesurant pas plus que 0,03 m3 (30 litres). Sensation mineure. Vous refroidissez, réchauffez ou parfumez au maximum 0,03 m3 (30 litres) de matière inerte pour 1 heure. Marque magique. Vous faites apparaitre une couleur, une petite marque ou un symbole sur un objet ou une surface, pendant 1 heure. Création mineure. Vous créez une babiole non magique, ou une image illusoire, qui peut tenir dans votre main. Il dure jusqu'à la fin de votre prochain tour. Une babiole ne peut pas infliger de dommage et n'a aucune valeur.",
  },
  {
    key: "produce-flame",
    name: "Flammes",
    level: 0,
    school: "conjuration",
    castingTime: "Action bonus",
    range: "Perso",
    components: { verbal: true, somatic: true, material: null },
    duration: "10 minutes",
    concentration: false,
    ritual: false,
    classLists: ["druid"],
    damage: { dice: "1d8", type: "fire", attackRoll: true, save: null },
    description: "Une flamme vacillante apparaît dans votre main et y reste pendant toute la durée du sort. Tant qu'elle est là, elle n'émet aucune chaleur, n'enflamme rien, et projette une Lumière vive sur un rayon de 6 mètres et une Lumière faible sur 6 mètres supplémentaires. Le sort prend fin si vous le relancez. Jusqu'à la fin du sort, vous pouvez prendre une action Magie pour lancer du feu sur une créature ou un objet dans un rayon de 18 mètres. Effectuez une attaque de sort à distance. Si l'attaque touche, la cible subit 1d8 dégâts de feu. Amélioration de sort mineur. Les dégâts augmentent de 1d8 lorsque vous atteignez les niveaux 5 (2d8), 11 (3d8) et 17 (4d8).",
  },
  {
    key: "protection-from-evil-and-good",
    name: "Protection contre le mal et le bien",
    level: 1,
    school: "abjuration",
    castingTime: "Action",
    range: "Contact",
    components: { verbal: true, somatic: true, material: "une flasque d'eau bénite d'une valeur minimale de 25 po, que le sort consomme" },
    duration: "Concentration, jusqu'à 10 minutes",
    concentration: true,
    ritual: false,
    classLists: ["cleric", "druid", "paladin", "warlock", "wizard"],
    damage: null,
    description: "Jusqu'à la fin du sort, une créature consentante que vous touchez est protégée contre les aberrations, célestes, élémentaires, fées, fiélons et morts-vivants. Cette protection confère plusieurs avantages. Ces créatures ont un Désavantage aux jets d'attaque contre la cible. De plus, la cible ne peut pas être possédée par ces créatures ni subir les états Charmé ou Effrayé. Si la cible est déjà possédée, charmée ou effrayée par de telles créatures, elle bénéficie d'un Avantage à tout nouveau jet de sauvegarde contre l'effet concerné.",
  },
  {
    key: "purify-food-and-drink",
    name: "Purification de la nourriture et de l'eau",
    level: 1,
    school: "transmutation",
    castingTime: "Action ou Rituel",
    range: "3 m",
    components: { verbal: true, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: true,
    classLists: ["cleric", "druid", "paladin"],
    damage: null,
    description: "Vous éliminez le poison et la pourriture des aliments et boissons non magiques dans une sphère de 1,50 mètre de rayon centrée sur un point à portée.",
  },
  {
    key: "ray-of-frost",
    name: "Rayon de givre",
    level: 0,
    school: "evocation",
    castingTime: "Action",
    range: "18 m",
    components: { verbal: true, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["sorcerer", "wizard"],
    damage: { dice: "1d8", type: "cold", attackRoll: true, save: null },
    description: "Un rayon de lumière glaciale bleu-blanc s'abat sur une créature à portée. Effectuez une attaque de sort à distance contre la cible. Si l'attaque touche, elle subit 1d8 dégâts de froid et sa Vitesse est réduite de 3 mètres jusqu'au début de votre prochain tour. Amélioration de sort mineur. Les dégâts augmentent de 1d8 aux niveaux 5 (2d8), 11 (3d8) et 17 (4d8).",
  },
  {
    key: "ray-of-sickness",
    name: "Rayon empoisonné",
    level: 1,
    school: "necromancy",
    castingTime: "Action",
    range: "18 m",
    components: { verbal: true, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["sorcerer", "wizard"],
    damage: { dice: "2d8", type: "poison", attackRoll: true, save: null },
    description: "Vous tirez un rayon verdâtre sur une créature à portée. Effectuez une attaque de sort à distance contre la cible. Si l'attaque touche, la cible subit 2d8 dégâts de poison et l'état Empoisonné jusqu'à la fin de votre prochain tour.",
  },
  {
    key: "resistance",
    name: "Résistance",
    level: 0,
    school: "abjuration",
    castingTime: "Action",
    range: "Contact",
    components: { verbal: true, somatic: true, material: null },
    duration: "Concentration, jusqu'à 1 minute",
    concentration: true,
    ritual: false,
    classLists: ["cleric", "druid"],
    damage: null,
    description: "Vous touchez une créature consentante et choisissez un type de dégâts : acide, contondant, froid, feu, foudre, nécrotique, perforant, poison, radiant, tranchant ou tonnerre. Si la créature subit des dégâts du type choisi avant la fin du sort, elle réduit le total des dégâts subis de 1d4. Une créature ne peut bénéficier de ce sort qu'une seule fois par tour.",
  },
  {
    key: "sacred-flame",
    name: "Flamme sacrée",
    level: 0,
    school: "evocation",
    castingTime: "Action",
    range: "18 m",
    components: { verbal: true, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["cleric"],
    damage: { dice: "1d8", type: "radiant", attackRoll: false, save: { ability: "dexterity", onSuccess: "none" } },
    description: "Une lueur semblable à une flamme s'abat sur une créature que vous pouvez voir à portée. La cible doit réussir un jet de sauvegarde de Dextérité ou subir 1d8 dégâts radiants. La cible ne bénéficie pas d'un Abri partiel (1/2) ni d'un Abri important (3/4) pour ce jet de sauvegarde. Amélioration de sort mineur. Les dégâts augmentent de 1d8 aux niveaux 5 (2d8), 11 (3d8) et 17 (4d8).",
  },
  {
    key: "sanctuary",
    name: "Sanctuaire",
    level: 1,
    school: "abjuration",
    castingTime: "Action bonus",
    range: "9 m",
    components: { verbal: true, somatic: true, material: "un éclat de verre issu d'un miroir" },
    duration: "1 minute",
    concentration: false,
    ritual: false,
    classLists: ["cleric"],
    damage: null,
    description: "Vous protégez une créature à portée. Jusqu'à la fin du sort, toute créature qui cible la créature protégée avec un jet d'attaque ou un sort qui inflige des dégâts doit réussir un jet de sauvegarde de Sagesse ou soit choisir une nouvelle cible, soit perdre l'attaque ou le sort. Ce sort ne protège pas la créature protégée des zones d'effet. Le sort prend fin si la créature protégée effectue un jet d'attaque, lance un sort ou inflige des dégâts.",
  },
  {
    key: "searing-smite",
    name: "Châtiment de fournaise",
    level: 1,
    school: "evocation",
    castingTime: "Action bonus",
    range: "Perso",
    components: { verbal: true, somatic: false, material: null },
    duration: "1 minute",
    concentration: false,
    ritual: false,
    classLists: ["paladin"],
    damage: { dice: "1d6", type: "fire", attackRoll: true, save: null },
    description: "Lorsque vous touchez la cible, elle subit 1d6 dégâts de feu supplémentaires. Au début de chacun de ses tours jusqu'à la fin du sort, la cible subit 1d6 dégâts de feu, puis effectue un jet de sauvegarde de Constitution. En cas d'échec, le sort continue. En cas de réussite, le sort prend fin.",
  },
  {
    key: "shield",
    name: "Bouclier",
    level: 1,
    school: "abjuration",
    castingTime: "Réaction",
    range: "Perso",
    components: { verbal: true, somatic: true, material: null },
    duration: "1 round",
    concentration: false,
    ritual: false,
    classLists: ["sorcerer", "wizard"],
    damage: null,
    description: "Une barrière imperceptible de force magique vous protège. Jusqu'au début de votre prochain tour, vous bénéficiez d'un bonus de +5 à la CA, y compris contre l'attaque déclenchante, et vous ne subissez aucun dégât de projectile magique.",
  },
  {
    key: "shield-of-faith",
    name: "Bouclier de la foi",
    level: 1,
    school: "abjuration",
    castingTime: "Action bonus",
    range: "18 m",
    components: { verbal: true, somatic: true, material: "un parchemin de prière" },
    duration: "Concentration, jusqu'à 10 minutes",
    concentration: true,
    ritual: false,
    classLists: ["cleric", "paladin"],
    damage: null,
    description: "Un champ scintillant entoure une créature de votre choix à portée, lui accordant un bonus de +2 à la CA pendant la durée du sort.",
  },
  {
    key: "shillelagh",
    name: "Crosse des druides",
    level: 0,
    school: "transmutation",
    castingTime: "Action bonus",
    range: "Perso",
    components: { verbal: true, somatic: true, material: "du gui" },
    duration: "1 minute",
    concentration: false,
    ritual: false,
    classLists: ["druid"],
    damage: null,
    description: "Le gourdin ou le bâton que vous tenez est imprégné de la puissance de la nature. Pour la durée du sort, vous pouvez utiliser votre caractéristique d'incantation au lieu de la Force pour les jets d'attaque et de dégâts des attaques au corps à corps avec cette arme, et le dé de dégâts de l'arme devient un d8. Si l'attaque inflige des dégâts, ceux-ci peuvent être de Force ou du type de dégâts normal de l'arme (selon votre choix). Le sort prend fin prématurément si vous le relancez ou si vous lâchez l'arme. Amélioration de sort mineur. Le dé de dégâts de l'arme change lorsque vous atteignez les niveaux 5 (d10), 11 (d12) et 17 (2d6).",
  },
  {
    key: "shocking-grasp",
    name: "Poigne électrique",
    level: 0,
    school: "evocation",
    castingTime: "Action",
    range: "Contact",
    components: { verbal: true, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["sorcerer", "wizard"],
    damage: { dice: "1d8", type: "lightning", attackRoll: true, save: null },
    description: "La foudre jaillit de vous vers une créature que vous tentez de toucher. Effectuez une attaque de sort au corps à corps contre la cible. Si l'attaque touche, la cible subit 1d8 dégâts de foudre et ne peut effectuer d'attaques d'opportunité avant le début de son prochain tour. Amélioration de sort mineur. Les dégâts augmentent de 1d8 lorsque vous atteignez les niveaux 5 (2d8), 11 (3d8) et 17 (4d8).",
  },
  {
    key: "silent-image",
    name: "Image silencieuse",
    level: 1,
    school: "illusion",
    castingTime: "Action",
    range: "18 m",
    components: { verbal: true, somatic: true, material: "un peu de laine brute" },
    duration: "Concentration, jusqu'à 10 minutes",
    concentration: true,
    ritual: false,
    classLists: ["bard", "sorcerer", "wizard"],
    damage: null,
    description: "Vous créez l'image d'un objet, d'une créature ou d'un autre phénomène visible ne dépassant pas un Cube de 4,50 mètres de côté. L'image apparaît à un endroit à portée et persiste pendant toute la durée du sort. L'image est purement visuelle ; elle n'est accompagnée d'aucun son, odeur ou autre effet sensoriel. Par une action Magie, vous pouvez déplacer l'image n'importe où à portée. Lorsque l'image change d'emplacement, vous pouvez modifier son apparence afin que ses mouvements paraissent naturels. Par exemple, si vous créez l'image d'une créature et que vous la déplacez, vous pouvez la modifier pour qu'elle semble marcher. Une interaction physique avec l'image révèle qu'il s'agit d'une illusion, car des objets peuvent la traverser. Une créature qui prend l'action Étude pour examiner l'image peut déterminer qu'il s'agit d'une illusion en réussissant un jet d'Intelligence (Investigation) contre le DD de sauvegarde de votre sort. Si une créature perçoit l'illusion pour ce qu'elle est, elle peut voir à travers l'image.",
  },
  {
    key: "sleep",
    name: "Sommeil",
    level: 1,
    school: "enchantment",
    castingTime: "Action",
    range: "18 m",
    components: { verbal: true, somatic: true, material: "une pincée de sable ou des pétales de rose" },
    duration: "Concentration, jusqu'à 1 minute",
    concentration: true,
    ritual: false,
    classLists: ["bard", "sorcerer", "wizard"],
    damage: null,
    description: "Toute créature de votre choix dans une sphère de 1,50 mètre de rayon centrée sur un point à portée doit réussir un jet de sauvegarde de Sagesse ou subir l'état Incapable d'agir jusqu'à la fin de son prochain tour, après quoi elle doit refaire le jet. Si la cible rate le deuxième jet de sauvegarde, elle subit l'état Inconscient pendant toute la durée du sort. Le sort prend fin si une cible subit des dégâts ou si une personne dans un rayon de 1,50 mètre entreprend une action pour la libérer de l'effet du sort. Les créatures qui ne dorment pas, comme les elfes, ou qui sont immunisées contre l'état Épuisement réussissent automatiquement leurs jets de sauvegarde contre ce sort.",
  },
  {
    key: "sorcerous-burst",
    name: "Éruption ensorcelée",
    level: 0,
    school: "evocation",
    castingTime: "Action",
    range: "36 m",
    components: { verbal: true, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["sorcerer"],
    damage: null,
    description: "Vous lancez une énergie ensorcelée sur une créature ou un objet à portée. Effectuez un jet d'attaque à distance contre la cible. Si l'attaque touche, la cible subit 1d8 dégâts du type de votre choix : acide, froid, feu, foudre, poison, psychique ou tonnerre. Si vous obtenez un 8 sur un d8 pour ce sort, vous pouvez lancer un autre d8 et l'ajouter aux dégâts. Lorsque vous lancez ce sort, le nombre maximal de d8 que vous pouvez ajouter aux dégâts du sort est égal à votre modificateur de caractéristique d'incantation. Amélioration de sort mineur. Ces dégâts augmentent de 1d8 lorsque vous atteignez les niveaux 5 (2d8), 11 (3d8) et 17 (4d8).",
  },
  {
    key: "spare-the-dying",
    name: "Stabilisation",
    level: 0,
    school: "necromancy",
    castingTime: "Action",
    range: "4,50 m",
    components: { verbal: true, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["cleric", "druid"],
    damage: null,
    description: "Choisissez une créature à portée qui est à 0 point de vie et qui n'est pas morte. La créature se stabilise. Amélioration de sort mineur. La portée est doublée aux niveaux 5 (9 mètres), 11 (18 mètres) et 17 (36 mètres).",
  },
  {
    key: "speak-with-animals",
    name: "Communication avec les animaux",
    level: 1,
    school: "divination",
    castingTime: "Action ou Rituel",
    range: "Perso",
    components: { verbal: true, somatic: true, material: null },
    duration: "10 minutes",
    concentration: false,
    ritual: true,
    classLists: ["bard", "druid", "ranger", "warlock"],
    damage: null,
    description: "Pendant toute la durée du sort, vous pouvez comprendre et communiquer verbalement avec des bêtes, et utiliser avec elles toutes les compétences de l'action Influencer. La plupart des bêtes ont peu de choses à dire sur des sujets autres que la survie ou la camaraderie, mais au minimum, une bête peut vous donner des informations sur les lieux et les monstres à proximité, y compris tout ce qu'elle a perçu au cours de la dernière journée.",
  },
  {
    key: "starry-wisp",
    name: "Poussière d'étoile",
    level: 0,
    school: "evocation",
    castingTime: "Action",
    range: "18 m",
    components: { verbal: true, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["bard", "druid"],
    damage: { dice: "1d8", type: "radiant", attackRoll: true, save: null },
    description: "Vous lancez un rayon de lumière sur une créature ou un objet à portée. Effectuez une attaque avec un sort à distance contre la cible. Si l'attaque touche, la cible subit 1d8 dégâts radiants et, jusqu'à la fin de votre prochain tour, émet une Lumière faible dans un rayon de 3 mètres et ne peut bénéficier de l'état Invisibilité. Amélioration de sort mineur. Les dégâts augmentent de 1d8 aux niveaux 5 (2d8), 11 (3d8) et 17 (4d8).",
  },
  {
    key: "tasha-s-hideous-laughter",
    name: "Fou rire de Tasha",
    level: 1,
    school: "enchantment",
    castingTime: "Action",
    range: "9 m",
    components: { verbal: true, somatic: true, material: "une tartelette et une plume" },
    duration: "Concentration, jusqu'à 1 minute",
    concentration: true,
    ritual: false,
    classLists: ["bard", "warlock", "wizard"],
    damage: null,
    description: "Une créature de votre choix que vous pouvez voir à portée effectue un jet de sauvegarde de Sagesse. En cas d'échec, elle subit les états À terre et Incapable d'agir pendant toute la durée du sort. Pendant ce temps, elle rit de manière incontrôlable si elle en est capable, et elle ne peut pas mettre fin à son état À terre. À la fin de chacun de ses tours et à chaque fois qu'elle subit des dégâts, elle effectue un nouveau jet de sauvegarde de Sagesse. La cible bénéficie d'un Avantage pour ce jet si celui-ci est déclenché par des dégâts. En cas de réussite, le sort prend fin.",
  },
  {
    key: "tenser-s-floating-disk",
    name: "Disque flottant de Tenser",
    level: 1,
    school: "conjuration",
    castingTime: "Action ou Rituel",
    range: "9 m",
    components: { verbal: true, somatic: true, material: "une goutte de mercure" },
    duration: "1 heure",
    concentration: false,
    ritual: true,
    classLists: ["wizard"],
    damage: null,
    description: "Ce sort crée un plan de force circulaire et horizontal, de 90 cm de diamètre et 2,50 cm d'épaisseur, flottant à 90 cm du sol dans un espace libre de votre choix que vous pouvez voir et à portée. Le disque reste en place pendant toute la durée du sort et peut supporter jusqu'à 250 kg. Si un poids supplémentaire est placé dessus, le sort prend fin et tout ce qui se trouve sur le disque tombe au sol. Le disque est immobile tant que vous n'êtes pas à plus de 6 mètres de lui. Si vous vous en éloignez de plus de 6 mètres, le disque vous suit et reste à 6 mètres ou moins de vous. Il peut se déplacer sur un terrain accidenté, monter ou descendre des escaliers, des pentes, etc, mais il ne peut pas franchir un dénivelé de 3 mètres ou plus. Par exemple, le disque ne peut pas franchir une fosse de 3 mètres de profondeur, ni en sortir s'il avait été créé au fond. Si vous vous éloignez de plus de 30 mètres du disque (généralement parce qu'il ne peut pas contourner un obstacle pour vous suivre), le sort prend fin.",
  },
  {
    key: "thaumaturgy",
    name: "Thaumaturgie",
    level: 0,
    school: "transmutation",
    castingTime: "Action",
    range: "9 m",
    components: { verbal: true, somatic: false, material: null },
    duration: "Jusqu'à 1 minute",
    concentration: false,
    ritual: false,
    classLists: ["cleric"],
    damage: null,
    description: "Vous engendrez un petit miracle dans la portée du sort. Choisissez l'effet dans les options ci-dessous. Si vous lancez ce sort plusieurs fois, vous pouvez garder actif jusqu'à trois de ses effets d'une minute simultanément. Yeux modifiés. Vous modifiez l'apparence de vos yeux pendant 1 minute. Voix retentissante. Votre voix résonne jusqu'à trois fois plus fort que d'habitude pendant 1 minute. Pendant cette durée, vous obtenez un Avantage aux jets de Charisme (Intimidation). Jeu avec le feu. Vous faites scintiller, s'intensifier, s'atténuer ou changer de couleur des flammes pendant 1 minute. Main invisible. Vous ouvrez ou fermez instantanément une porte ou une fenêtre non verrouillée. Bruit fantôme. Vous créez un son bref provenant d'un point de votre choix à portée, comme un grondement de tonnerre, le cri d'un corbeau ou des murmures inquiétants. Secousse. Vous provoquez un tremblement de terre inoffensif pendant 1 minute.",
  },
  {
    key: "thorn-whip",
    name: "Fouet épineux",
    level: 0,
    school: "transmutation",
    castingTime: "Action",
    range: "9 m",
    components: { verbal: true, somatic: true, material: "une tige de plante épineuse" },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["druid"],
    damage: { dice: "1d6", type: "piercing", attackRoll: true, save: null },
    description: "Vous créez un fouet semblable à une liane couverte d'épines qui s'abat à votre ordre sur une créature à portée. Effectuez une attaque de sort au corps à corps contre la cible. Si l'attaque touche, la cible subit 1d6 dégâts perforants, et si elle est de taille G ou inférieure, vous pouvez la rapprocher de vous jusqu'à 3 mètres. Amélioration de sort mineur. Les dégâts augmentent de 1d6 aux niveaux 5 (2d6), 11 (3d6) et 17 (4d6).",
  },
  {
    key: "thunderclap",
    name: "Coup de tonnerre",
    level: 0,
    school: "evocation",
    castingTime: "Action",
    range: "Perso",
    components: { verbal: false, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["bard", "druid", "sorcerer", "warlock", "wizard"],
    damage: { dice: "1d6", type: "thunder", attackRoll: false, save: { ability: "constitution", onSuccess: "none" } },
    description: "Toute créature dans une Émanation de 1,50 mètre provenant de vous doit réussir un jet de sauvegarde de Constitution ou subir 1d6 dégâts de tonnerre. Le son tonitruant du sort peut être entendu jusqu'à 30 mètres. Amélioration de sort mineur. Les dégâts augmentent de 1d6 lorsque vous atteignez les niveaux 5 (2d6), 11 (3d6) et 17 (4d6).",
  },
  {
    key: "thunderous-smite",
    name: "Châtiment de tonnerre",
    level: 1,
    school: "evocation",
    castingTime: "Action bonus",
    range: "Perso",
    components: { verbal: true, somatic: false, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["paladin"],
    damage: { dice: "2d6", type: "thunder", attackRoll: true, save: null },
    description: "Votre coup retentit comme le tonnerre dans un rayon de 90 mètres, et la cible subit 2d6 dégâts de tonnerre supplémentaires. De plus, si la cible est une créature, elle doit réussir un jet de sauvegarde de Force ou être repoussée à 3 mètres de vous et subir l'état À terre.",
  },
  {
    key: "thunderwave",
    name: "Vague tonnante",
    level: 1,
    school: "evocation",
    castingTime: "Action",
    range: "Perso",
    components: { verbal: true, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["bard", "druid", "sorcerer", "wizard"],
    damage: { dice: "2d8", type: "thunder", attackRoll: false, save: { ability: "constitution", onSuccess: "half" } },
    description: "Vous déchaînez une vague d'énergie tonitruante. Toute créature dans un Cube de 4,50 mètres de côté provenant de vous effectue un jet de sauvegarde de Constitution. En cas d'échec, une créature subit 2d8 dégâts de tonnerre et est repoussée de 3 mètres. En cas de réussite, elle subit seulement la moitié des dégâts. De plus, les objets non sécurisés entièrement à l'intérieur du Cube sont repoussés de 3 mètres, et un grondement tonitruant retentit dans un rayon de 90 mètres.",
  },
  {
    key: "toll-the-dead",
    name: "Glas",
    level: 0,
    school: "necromancy",
    castingTime: "Action",
    range: "18 m",
    components: { verbal: true, somatic: true, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["cleric", "warlock", "wizard"],
    damage: { dice: "1d8", type: "necrotic", attackRoll: false, save: { ability: "wisdom", onSuccess: "none" } },
    description: "Vous pointez une créature que vous pouvez voir à portée, et le son d'une cloche douloureuse retentit jusqu'à 3 mètres de la cible. Celle-ci doit réussir un jet de sauvegarde de Sagesse ou subir 1d8 dégâts nécrotiques. Si elle n'a plus tous ses points de vie, elle subit 1d12 dégâts nécrotiques au lieu de cela. Amélioration de sort mineur. Les dégâts augmentent d'un dé aux niveaux 5 (2d8 ou 2d12), 11 (3d8 ou 3d12) et 17 (4d8 ou 4d12).",
  },
  {
    key: "true-strike",
    name: "Coup au but",
    level: 0,
    school: "divination",
    castingTime: "Action",
    range: "Perso",
    components: { verbal: false, somatic: true, material: "une arme que vous maîtrisez et d'une valeur minimale de 1 pc" },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["bard", "sorcerer", "warlock", "wizard"],
    damage: null,
    description: "Guidé par un éclair magique, vous effectuez une attaque avec l'arme utilisée pour lancer le sort. L'attaque utilise votre caractéristique d'incantation pour les jets d'attaque et de dégâts, au lieu d'utiliser la Force ou la Dextérité. Si l'attaque inflige des dégâts, ceux-ci peuvent être radiants ou du type de dégâts normal de l'arme (selon votre choix). Amélioration de sort mineur. Que vous infligiez des dégâts radiants ou du type de dégâts normal de l'arme, l'attaque inflige des dégâts radiants supplémentaires aux niveaux 5 (1d6), 11 (2d6) et 17 (3d6).",
  },
  {
    key: "unseen-servant",
    name: "Serviteur invisible",
    level: 1,
    school: "conjuration",
    castingTime: "Action ou Rituel",
    range: "18 m",
    components: { verbal: true, somatic: true, material: "un bout de ficelle et un morceau de bois" },
    duration: "1 heure",
    concentration: false,
    ritual: true,
    classLists: ["bard", "warlock", "wizard"],
    damage: null,
    description: "Ce sort crée une force invisible, inerte et informe de taille M qui accomplit des tâches simples à votre demande jusqu'à la fin du sort. Le serviteur apparaît dans un espace libre au sol, à portée. Il a une CA de 10, 1 point de vie, une force de 2, et ne peut pas attaquer. S'il tombe à 0 point de vie, le sort prend fin. Une fois par tour, par une action Bonus, vous pouvez ordonner mentalement au serviteur de se déplacer jusqu'à 4,50 mètres et d'interagir avec un objet. Le serviteur peut effectuer des tâches simples qu'un humain pourrait effectuer, comme aller chercher des objets, nettoyer, raccommoder, plier des vêtements, allumer du feu, servir à manger et à boire. Une fois l'ordre donné, le serviteur exécute la tâche au mieux de ses capacités jusqu'à ce qu'il l'ait accomplie, puis attend votre prochain ordre. Si vous ordonnez au serviteur d'effectuer une tâche qui l'éloignerait de plus de 18 mètres de vous, le sort prend fin.",
  },
  {
    key: "vicious-mockery",
    name: "Moquerie cruelle",
    level: 0,
    school: "enchantment",
    castingTime: "Action",
    range: "18 m",
    components: { verbal: true, somatic: false, material: null },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["bard"],
    damage: { dice: "1d6", type: "psychic", attackRoll: false, save: { ability: "wisdom", onSuccess: "none" } },
    description: "Vous lancez une salve d'insultes mêlée à de subtils enchantements sur une créature que vous pouvez voir ou entendre à portée. La cible doit réussir un jet de sauvegarde de Sagesse ou subir 1d6 dégâts psychiques. Elle obtient de plus un Désavantage lors de son prochain jet d'attaque avant la fin de son prochain tour. Amélioration de sort mineur. Les dégâts augmentent de 1d6 lorsque vous atteignez le niveau 5 (2d6), le niveau 11 (3d6) et le niveau 17 (4d6).",
  },
  {
    key: "witch-bolt",
    name: "Trait ensorcelé",
    level: 1,
    school: "evocation",
    castingTime: "Action",
    range: "18 m",
    components: { verbal: true, somatic: true, material: "une petite branche frappée par la foudre" },
    duration: "Concentration, jusqu'à 1 minute",
    concentration: true,
    ritual: false,
    classLists: ["sorcerer", "warlock", "wizard"],
    damage: { dice: "2d12", type: "lightning", attackRoll: true, save: null },
    description: "Un rayon d'énergie crépitante se dirige vers une créature à portée, formant un arc de foudre entre vous et la cible. Effectuez une attaque de sort à distance contre elle. Si l'attaque touche, la cible subit 2d12 dégâts de foudre. À chacun de vos tours suivants, vous pouvez prendre une action Bonus pour infliger automatiquement 1d12 dégâts de foudre à la cible, même si la première attaque a échoué. Le sort prend fin si la cible se trouve hors de portée du sort ou si elle bénéficie d'un Abri total contre vous.",
  },
  {
    key: "word-of-radiance",
    name: "Mot de radiance",
    level: 0,
    school: "evocation",
    castingTime: "Action",
    range: "Perso",
    components: { verbal: true, somatic: false, material: "un symbole en forme de soleil" },
    duration: "Instantanée",
    concentration: false,
    ritual: false,
    classLists: ["cleric"],
    damage: { dice: "1d6", type: "radiant", attackRoll: false, save: { ability: "constitution", onSuccess: "none" } },
    description: "Une radiance brûlante jaillit de vous sous forme d'Émanation de 1,50 mètre. Chaque créature de votre choix que vous pouvez voir doit réussir un jet de sauvegarde de Constitution ou subir 1d6 dégâts radiants. Amélioration de sort mineur. Les dégâts augmentent de 1d6 aux niveaux 5 (2d6), 11 (3d6) et 17 (4d6).",
  },
  {
    key: "wrathful-smite",
    name: "Châtiment de courroux",
    level: 1,
    school: "necromancy",
    castingTime: "Action bonus",
    range: "Perso",
    components: { verbal: true, somatic: false, material: null },
    duration: "1 minute",
    concentration: false,
    ritual: false,
    classLists: ["paladin"],
    damage: { dice: "1d6", type: "necrotic", attackRoll: true, save: null },
    description: "La cible subit 1d6 dégâts nécrotiques supplémentaires suite à l'attaque, et doit réussir un jet de sauvegarde de Sagesse ou subir l'état Effrayé jusqu'à la fin du sort. À la fin de chacun de ses tours, la cible effrayée renouvelle son jet de sauvegarde, mettant fin au sort sur elle-même en cas de réussite.",
  },
];

export const SPELLS: Readonly<Record<SpellKey, Spell>> = Object.fromEntries(
  SPELL_LIST.map((spell) => [spell.key, spell]),
);

export const SPELL_KEYS: readonly SpellKey[] = SPELL_LIST.map((spell) => spell.key);

/** Les sorts qu'une classe peut préparer au niveau 1, sorts mineurs compris. */
export function spellsAvailableTo(classKey: ClassKey): readonly Spell[] {
  return SPELL_LIST.filter((spell) => spell.classLists.includes(classKey));
}
