export const TRINKET_NAMES = [
  'Une main de gobelin momifiée',
  'Un cristal qui brille faiblement au clair de lune',
  "Une pièce d'or frappée dans un pays inconnu",
  'Un journal écrit dans une langue que vous ne connaissez pas',
  'Une bague en cuivre qui ne ternit jamais',
  "Une vieille pièce d'échecs en verre",
  "Une paire de dés en osselet, chacun portant un crâne sur la face qui devrait indiquer le 6",
  "Une petite idole représentant une créature cauchemardesque qui provoque des rêves troublants quand vous dormez près d'elle",
  "Une mèche de cheveux appartenant à quelqu'un",
  "Le titre de propriété d'une parcelle située dans un royaume qui vous est inconnu",
  "Un bloc de 30 grammes d'un matériau inconnu",
  "Une petite poupée de tissu hérissée d'aiguilles",
  "Une dent provenant d'une bête inconnue",
  "Une énorme écaille, peut-être celle d'un dragon",
  'Une plume vert vif',
  'Une vieille carte de divination à votre effigie',
  'Un orbe de verre empli de fumée mouvante',
  'Un œuf de 500 grammes à la coquille rouge vif',
  'Une pipe qui fait des bulles',
  'Un bocal contenant un morceau de chair flottant dans la saumure',
  'Une boîte à musique de facture gnome qui joue une chanson vous rappelant vaguement votre enfance',
  "Une statuette en bois représentant un halfelin à l'air satisfait",
  'Un orbe en cuivre gravé de runes étranges',
  'Un disque de pierre multicolore',
  'Une icône de corbeau en argent',
  "Un sac contenant quarante-sept dents, dont l'une est pourrie",
  "Un éclat d'obsidienne toujours chaud au toucher",
  "Une griffe de dragon suspendue à un collier de cuir",
  'Une paire de vieilles chaussettes',
  "Un livre vierge dont les pages refusent de retenir l'encre, la craie, le graphite ou toute autre marque",
  "Un insigne en argent en forme d'étoile à cinq branches",
  'Un couteau ayant appartenu à un membre de votre famille',
  "Une fiole de verre pleine de rognures d'ongles",
  "Un objet métallique rectangulaire muni de deux petites coupelles qui produit des étincelles lorsqu'on le mouille",
  'Un gant blanc à paillettes destiné à un humain',
  'Une veste dotée de cent petites poches',
  'Une pierre qui ne pèse rien',
  "Un dessin représentant un gobelin",
  "Une fiole de verre vide qui sent le parfum",
  'Une gemme que toute autre personne prend pour un morceau de charbon',
  "Un morceau de tissu provenant d'une vieille bannière",
  "Un insigne de grade provenant d'un légionnaire disparu",
  'Une cloche en argent sans battant',
  "Un canari mécanique à l'intérieur d'une lampe",
  'Un coffre miniature sculpté de nombreux pieds sous sa base',
  "Un esprit follet mort dans une bouteille de verre transparent",
  "Une boîte métallique sans ouverture qui semble contenir du liquide, du sable, des araignées ou du verre brisé, au choix",
  "Un orbe de verre rempli d'eau où nage un poisson rouge mécanique",
  'Une cuillère en argent gravée de la lettre M sur le manche',
  'Un sifflet en bois doré',
  'Un scarabée mort aussi gros que votre main',
  "Deux soldats de plomb, dont l'un est décapité",
  'Une petite boîte remplie de boutons de différentes tailles',
  "Une bougie qu'il est impossible d'allumer",
  'Une cage miniature sans porte',
  'Une vieille clé',
  'Une carte au trésor indéchiffrable',
  "La poignée d'une épée brisée",
  'Une patte de lapin',
  'Un œil de verre',
  "Un camée représentant une personne hideuse",
  "Un crâne en argent de la taille d'une pièce de monnaie",
  "Un masque d'albâtre",
  "Un cône d'encens noir et collant à l'odeur infecte",
  'Un bonnet de nuit qui vous procure des rêves agréables lorsque vous le portez',
  "Une chausse-trappe faite d'un os",
  'Une monture de monocle en or dépourvue de verre',
  'Un cube de 2,5 centimètres dont chaque face est de couleur différente',
  'Un bouton de porte en cristal',
  'Un petit paquet rempli de poussière rose',
  "Un fragment d'une belle chanson, noté sur deux morceaux de parchemin",
  "Une boucle d'oreille en forme de larme d'argent contenant une véritable larme",
  "Une coquille d'œuf peinte de scènes de misère aux détails troublants",
  'Un éventail qui, une fois déplié, montre un chat endormi',
  "Un ensemble de flûtes en os",
  "Un trèfle à quatre feuilles pressé dans un livre sur les bonnes manières et l'étiquette",
  'Une feuille de parchemin représentant un engin mécanique',
  "Un fourreau orné qui ne convient à aucune lame que vous avez trouvée",
  "Une invitation à une fête au cours de laquelle un meurtre a eu lieu",
  "Un pentacle en bronze gravé d'une tête de rat en son centre",
  "Un mouchoir violet brodé au nom d'un archimage",
  "La moitié du plan d'un temple, d'un château ou d'une autre structure",
  'Un morceau de tissu plié qui se transforme en chapeau élégant une fois déplié',
  "Un reçu de dépôt provenant d'une banque située dans une ville lointaine",
  'Un journal auquel il manque sept pages',
  'Une tabatière en argent vide portant le mot « rêves » sur son couvercle',
  'Un symbole sacré en fer consacré à un dieu inconnu',
  "Un livre relatant l'ascension et la chute d'un héros légendaire, auquel manque le dernier chapitre",
  'Une fiole de sang de dragon',
  'Une ancienne flèche de facture elfique',
  'Une aiguille qui ne se plie jamais',
  'Une broche ouvragée de facture naine',
  'Une bouteille de vin vide étiquetée « Domaine du Magicien des Vins, Cuvée du Dragon Rouge, 331422-W »',
  'Un carreau de mosaïque à la surface émaillée multicolore',
  'Une souris pétrifiée',
  "Un drapeau pirate noir orné d'un crâne de dragon et de tibias croisés",
  "Un minuscule crabe ou une araignée mécanique qui se déplace lorsqu'on ne l'observe pas",
  'Un bocal de saindoux étiqueté « Graisse de griffon »',
  "Une boîte en bois à fond de céramique contenant un ver vivant doté d'une tête à chaque extrémité",
  "Une urne en métal contenant les cendres d'un héros",
] as const;
