// Les armes de D&D 2024, courantes et de guerre.
// Source : docs/characteres/equipment/weapons.json
//
// ATTENTION : cette table n'est plus lue à l'exécution — les statistiques d'arme
// vivent dans la collection `items`. Elle reste la forme normalisée d'où
// `items.seed.json` a été produit, et ce que `reference.test.ts` surveille.
//
// Les propriétés y étaient en prose française (« Lancer (portée 6/18) ») : elles
// sont ici un vocabulaire fermé, et la portée est un champ à part.

import type { DamageType } from './proficiencies';

export type WeaponCategory = 'simple' | 'martial';

export type WeaponRangeKind = 'melee' | 'ranged';

export const WEAPON_PROPERTIES = [
  'ammunition',
  'finesse',
  'heavy',
  'light',
  'loading',
  'reach',
  'thrown',
  'twoHanded',
  'versatile',
] as const;

export type WeaponProperty = (typeof WEAPON_PROPERTIES)[number];

export interface WeaponRange {
  normal: number;
  max: number;
}

export interface Weapon {
  key: string;
  name: string;
  category: WeaponCategory;
  kind: WeaponRangeKind;
  damageDice: string;
  damageType: DamageType;
  /** Dés de dégâts à deux mains, pour les armes Polyvalentes. */
  versatileDice: string | null;
  range: WeaponRange | null;
  properties: readonly WeaponProperty[];
}

const WEAPON_LIST: readonly Weapon[] = [
  // -- Armes courantes de corps à corps ------------------------------------
  {
    key: 'quarterstaff',
    name: 'Bâton de combat',
    category: 'simple',
    kind: 'melee',
    damageDice: '1d6',
    damageType: 'bludgeoning',
    versatileDice: '1d8',
    range: null,
    properties: ['versatile'],
  },
  {
    key: 'dagger',
    name: 'Dague',
    category: 'simple',
    kind: 'melee',
    damageDice: '1d4',
    damageType: 'piercing',
    versatileDice: null,
    range: { normal: 6, max: 18 },
    properties: ['finesse', 'light', 'thrown'],
  },
  {
    key: 'club',
    name: 'Gourdin',
    category: 'simple',
    kind: 'melee',
    damageDice: '1d4',
    damageType: 'bludgeoning',
    versatileDice: null,
    range: null,
    properties: ['light'],
  },
  {
    key: 'handaxe',
    name: 'Hachette',
    category: 'simple',
    kind: 'melee',
    damageDice: '1d6',
    damageType: 'slashing',
    versatileDice: null,
    range: { normal: 6, max: 18 },
    properties: ['light', 'thrown'],
  },
  {
    key: 'javelin',
    name: 'Javeline',
    category: 'simple',
    kind: 'melee',
    damageDice: '1d6',
    damageType: 'piercing',
    versatileDice: null,
    range: { normal: 9, max: 36 },
    properties: ['thrown'],
  },
  {
    key: 'spear',
    name: 'Lance',
    category: 'simple',
    kind: 'melee',
    damageDice: '1d6',
    damageType: 'piercing',
    versatileDice: '1d8',
    range: { normal: 6, max: 18 },
    properties: ['thrown', 'versatile'],
  },
  {
    key: 'light-hammer',
    name: 'Marteau léger',
    category: 'simple',
    kind: 'melee',
    damageDice: '1d4',
    damageType: 'bludgeoning',
    versatileDice: null,
    range: { normal: 6, max: 18 },
    properties: ['light', 'thrown'],
  },
  {
    key: 'mace',
    name: "Masse d'armes",
    category: 'simple',
    kind: 'melee',
    damageDice: '1d6',
    damageType: 'bludgeoning',
    versatileDice: null,
    range: null,
    properties: [],
  },
  {
    key: 'greatclub',
    name: 'Massue',
    category: 'simple',
    kind: 'melee',
    damageDice: '1d8',
    damageType: 'bludgeoning',
    versatileDice: null,
    range: null,
    properties: ['twoHanded'],
  },
  {
    key: 'sickle',
    name: 'Serpe',
    category: 'simple',
    kind: 'melee',
    damageDice: '1d4',
    damageType: 'slashing',
    versatileDice: null,
    range: null,
    properties: ['light'],
  },

  // -- Armes courantes à distance ------------------------------------------
  {
    key: 'light-crossbow',
    name: 'Arbalète légère',
    category: 'simple',
    kind: 'ranged',
    damageDice: '1d8',
    damageType: 'piercing',
    versatileDice: null,
    range: { normal: 24, max: 96 },
    properties: ['ammunition', 'loading', 'twoHanded'],
  },
  {
    key: 'shortbow',
    name: 'Arc court',
    category: 'simple',
    kind: 'ranged',
    damageDice: '1d6',
    damageType: 'piercing',
    versatileDice: null,
    range: { normal: 24, max: 96 },
    properties: ['ammunition', 'twoHanded'],
  },
  {
    key: 'dart',
    name: 'Fléchette',
    category: 'simple',
    kind: 'ranged',
    damageDice: '1d4',
    damageType: 'piercing',
    versatileDice: null,
    range: { normal: 6, max: 18 },
    properties: ['finesse', 'thrown'],
  },
  {
    key: 'sling',
    name: 'Fronde',
    category: 'simple',
    kind: 'ranged',
    damageDice: '1d4',
    damageType: 'bludgeoning',
    versatileDice: null,
    range: { normal: 9, max: 36 },
    properties: ['ammunition'],
  },

  // -- Armes de guerre de corps à corps ------------------------------------
  {
    key: 'scimitar',
    name: 'Cimeterre',
    category: 'martial',
    kind: 'melee',
    damageDice: '1d6',
    damageType: 'slashing',
    versatileDice: null,
    range: null,
    properties: ['finesse', 'light'],
  },
  {
    key: 'glaive',
    name: 'Coutille',
    category: 'martial',
    kind: 'melee',
    damageDice: '1d10',
    damageType: 'slashing',
    versatileDice: null,
    range: null,
    properties: ['heavy', 'reach', 'twoHanded'],
  },
  {
    key: 'greatsword',
    name: 'Épée à deux mains',
    category: 'martial',
    kind: 'melee',
    damageDice: '2d6',
    damageType: 'slashing',
    versatileDice: null,
    range: null,
    properties: ['heavy', 'twoHanded'],
  },
  {
    key: 'shortsword',
    name: 'Épée courte',
    category: 'martial',
    kind: 'melee',
    damageDice: '1d6',
    damageType: 'piercing',
    versatileDice: null,
    range: null,
    properties: ['finesse', 'light'],
  },
  {
    key: 'longsword',
    name: 'Épée longue',
    category: 'martial',
    kind: 'melee',
    damageDice: '1d8',
    damageType: 'slashing',
    versatileDice: '1d10',
    range: null,
    properties: ['versatile'],
  },
  {
    key: 'flail',
    name: "Fléau d'armes",
    category: 'martial',
    kind: 'melee',
    damageDice: '1d8',
    damageType: 'bludgeoning',
    versatileDice: null,
    range: null,
    properties: [],
  },
  {
    key: 'whip',
    name: 'Fouet',
    category: 'martial',
    kind: 'melee',
    damageDice: '1d4',
    damageType: 'slashing',
    versatileDice: null,
    range: null,
    properties: ['finesse', 'reach'],
  },
  {
    key: 'greataxe',
    name: 'Hache à deux mains',
    category: 'martial',
    kind: 'melee',
    damageDice: '1d12',
    damageType: 'slashing',
    versatileDice: null,
    range: null,
    properties: ['heavy', 'twoHanded'],
  },
  {
    key: 'battleaxe',
    name: "Hache d'armes",
    category: 'martial',
    kind: 'melee',
    damageDice: '1d8',
    damageType: 'slashing',
    versatileDice: '1d10',
    range: null,
    properties: ['versatile'],
  },
  {
    key: 'halberd',
    name: 'Hallebarde',
    category: 'martial',
    kind: 'melee',
    damageDice: '1d10',
    damageType: 'slashing',
    versatileDice: null,
    range: null,
    properties: ['heavy', 'reach', 'twoHanded'],
  },
  {
    key: 'lance',
    name: "Lance d'arçon",
    category: 'martial',
    kind: 'melee',
    damageDice: '1d10',
    damageType: 'piercing',
    versatileDice: null,
    range: null,
    properties: ['heavy', 'reach', 'twoHanded'],
  },
  {
    key: 'maul',
    name: "Maillet d'armes",
    category: 'martial',
    kind: 'melee',
    damageDice: '2d6',
    damageType: 'bludgeoning',
    versatileDice: null,
    range: null,
    properties: ['heavy', 'twoHanded'],
  },
  {
    key: 'warhammer',
    name: 'Marteau de guerre',
    category: 'martial',
    kind: 'melee',
    damageDice: '1d8',
    damageType: 'bludgeoning',
    versatileDice: '1d10',
    range: null,
    properties: ['versatile'],
  },
  {
    key: 'morningstar',
    name: 'Morgenstern',
    category: 'martial',
    kind: 'melee',
    damageDice: '1d8',
    damageType: 'piercing',
    versatileDice: null,
    range: null,
    properties: [],
  },
  {
    key: 'war-pick',
    name: 'Pic de guerre',
    category: 'martial',
    kind: 'melee',
    damageDice: '1d8',
    damageType: 'piercing',
    versatileDice: '1d10',
    range: null,
    properties: ['versatile'],
  },
  {
    key: 'pike',
    name: 'Pique',
    category: 'martial',
    kind: 'melee',
    damageDice: '1d10',
    damageType: 'piercing',
    versatileDice: null,
    range: null,
    properties: ['heavy', 'reach', 'twoHanded'],
  },
  {
    key: 'rapier',
    name: 'Rapière',
    category: 'martial',
    kind: 'melee',
    damageDice: '1d8',
    damageType: 'piercing',
    versatileDice: null,
    range: null,
    properties: ['finesse'],
  },
  {
    key: 'trident',
    name: 'Trident',
    category: 'martial',
    kind: 'melee',
    damageDice: '1d8',
    damageType: 'piercing',
    versatileDice: '1d10',
    range: { normal: 6, max: 18 },
    properties: ['thrown', 'versatile'],
  },

  // -- Armes de guerre à distance ------------------------------------------
  {
    key: 'hand-crossbow',
    name: 'Arbalète de poing',
    category: 'martial',
    kind: 'ranged',
    damageDice: '1d6',
    damageType: 'piercing',
    versatileDice: null,
    range: { normal: 9, max: 36 },
    properties: ['ammunition', 'light', 'loading'],
  },
  {
    key: 'heavy-crossbow',
    name: 'Arbalète lourde',
    category: 'martial',
    kind: 'ranged',
    damageDice: '1d10',
    damageType: 'piercing',
    versatileDice: null,
    range: { normal: 30, max: 120 },
    properties: ['ammunition', 'heavy', 'loading', 'twoHanded'],
  },
  {
    key: 'longbow',
    name: 'Arc long',
    category: 'martial',
    kind: 'ranged',
    damageDice: '1d8',
    damageType: 'piercing',
    versatileDice: null,
    range: { normal: 45, max: 180 },
    properties: ['ammunition', 'heavy', 'twoHanded'],
  },
  {
    key: 'musket',
    name: 'Mousquet',
    category: 'martial',
    kind: 'ranged',
    damageDice: '1d12',
    damageType: 'piercing',
    versatileDice: null,
    range: { normal: 12, max: 36 },
    properties: ['ammunition', 'loading', 'twoHanded'],
  },
  {
    key: 'pistol',
    name: 'Pistolet',
    category: 'martial',
    kind: 'ranged',
    damageDice: '1d10',
    damageType: 'piercing',
    versatileDice: null,
    range: { normal: 9, max: 27 },
    properties: ['ammunition', 'loading'],
  },
  {
    key: 'blowgun',
    name: 'Sarbacane',
    category: 'martial',
    kind: 'ranged',
    damageDice: '1',
    damageType: 'piercing',
    versatileDice: null,
    range: { normal: 7.5, max: 30 },
    properties: ['ammunition', 'loading'],
  },
];

export const WEAPONS: Readonly<Record<string, Weapon>> = Object.fromEntries(
  WEAPON_LIST.map((weapon) => [weapon.key, weapon]),
);

export const WEAPON_KEYS: readonly string[] = WEAPON_LIST.map((weapon) => weapon.key);
